/* ************************************************************************** */
/** DDR2 SDRAM Controller Driver

  @Company
    Marquette Senior Design E44

  @File Name
    ddr2.c

  @Summary
    Driver for the PIC32MZ2064DAR176's stacked-in-package 32MB DDR2 SDRAM

  @Description
    See ddr2.h for the memory map and integration notes. This file derives
    every DDR2 controller/PHY register value from:
      - This device's fixed DDR2 geometry and timing (PIC32MZ-DA family data
        sheet DS60001565, section 4.2 "DDR2 SDRAM" and Table 44-55 "DDR2
        SDRAM Timing Specifications"),
      - The register field formulas in the PIC32 Family Reference Manual,
        Section 55 "DDR SDRAM Controller" (DS60001321), Table 55-4, and
      - The standard JEDEC DDR2 (JESD79-2F) Mode/Extended Mode Register
        encodings (identical across every DDR2 vendor's datasheet).

    A handful of XC32 device-header bitfield definitions for this part
    disagree with the family reference manual's documented bit positions
    (confirmed for DDRMEMCFG4: the header widens BNKADDRMSK/CSADDRMSK to 5
    bits each where the manual specifies 3, shifting CSADDRMSK to the wrong
    bit). To avoid relying on other, unchecked bitfield names in the same
    register file, every register below that isn't a single full-width
    field is written as one masked/shifted 32-bit value with the bit
    position cited in the comment, rather than through the compiler's ".bits"
    struct.
 */
/* ************************************************************************** */

#include <xc.h>
#include <stdio.h>
#include <string.h>

#include "ddr2.h"
#include "device_control.h"
#include "terminal_control.h"
#include "error_handler.h"

// ---- SDRAM timing parameters, from the PIC32MZ-DA family data sheet
// (DS60001565) Table 44-55 "DDR2 SDRAM Timing Specifications" -- these
// describe the actual 32MB DDR2 die stacked in this part's package, not a
// generic/external DDR2 chip ----
#define DDR2_TRFC_NS            75     // DDR16: auto-refresh cycle time
#define DDR2_TWR_NS             15     // DDR21: write recovery time
#define DDR2_TWTR_NS            10     // DDR22: internal write-to-read delay
#define DDR2_TRP_NS             20     // DDR13: precharge-to-active delay
#define DDR2_TRCD_NS            20     // DDR12: active-to-read/write delay
#define DDR2_TRRD_NS            10     // DDR19: row-to-row (RAS-to-RAS) delay, 1KB page
#define DDR2_TRTP_NS            10     // DDR23: internal read-to-precharge delay
#define DDR2_TRAS_NS            40     // DDR15: active-to-precharge minimum delay
#define DDR2_TRC_NS             65     // DDR14: row cycle time
#define DDR2_TFAW_NS            35     // DDR20: four-bank activation window, 1KB page
#define DDR2_TDLLK_DRAM_CLKS    200    // Standard JEDEC DDR2 DLL lock time (also this part's tXSRD, DDR24)
#define DDR2_TCKE_DRAM_CLKS     3      // DDR18: CKE minimum high/low pulse width
#define DDR2_TXP_DRAM_CLKS      2      // DDR25: exit precharge power-down delay
#define DDR2_TMRD_DRAM_CLKS     2      // DDR26: Mode Register Set command cycle delay
// Average refresh interval for -40C to 85C Tj (DDR17); halve this if the
// board can run hotter than 85C junction temperature
#define DDR2_TREFI_NS           7800

// ---- Speed grade (DS60001565 Table 44-55, DDR27-30). CL = 3 is this
// part's fastest supported CAS latency at its max clock (see DDR2_TCK_NS
// below); AL (posted CAS additive latency) is left at 0, unused ----
#define DDR2_CAS_LATENCY        3
#define DDR2_READ_LATENCY       DDR2_CAS_LATENCY               // RL = AL + CL
#define DDR2_WRITE_LATENCY      (DDR2_READ_LATENCY - 1)         // WL = RL - 1 (DDR29)

// ---- DDR2 (DRAM-side) clock: 200MHz, this part's fastest rated speed
// (DDR10 tCK min = 5ns). Generated by the dedicated Memory PLL (MPLL) from
// the same 24MHz POSC used for SYSCLK -- see ddr2MPLLInitialize().
// This board's POSC is 24MHz (external clock, POSCMOD=EC). The input divider
// brings it to 12MHz at the MPLL phase detector so the rest of the chain is
// unchanged: MFVCO = (24MHz / 2) * 100 = 1200MHz (within the MPLL's
// 400-1600MHz VCO range), MFMPLL = 1200MHz / 6 = 200MHz.
// NOTE: with INPUT_DIVIDER = 1 (as if POSC were 12MHz) the VCO runs at 2400MHz
// and the DRAM clock at 400MHz -- 2x the DRAM's rated max, so self-calibration
// can never pass. Keep the input divider matched to the actual POSC frequency.
#define DDR2_MPLL_INPUT_DIVIDER     2
#define DDR2_MPLL_MULTIPLIER        100
#define DDR2_MPLL_OUTPUT_DIVIDER1   6
#define DDR2_MPLL_OUTPUT_DIVIDER2   1
#define DDR2_TCK_NS                 5

// The controller runs in half-rate mode (required on this device): its
// clock is half the DDR2 clock, so its period is twice the DRAM clock
// period. PIC32 FRM Table 55-4 calls this CTL_CLK_PER.
#define DDR2_CTL_CLK_PERIOD_NS      (DDR2_TCK_NS * 2)
// Burst length in *controller* clock cycles for half-rate mode (always 8 on
// the DRAM side; PIC32 FRM 55.3.1 "Burst length in cycles = 2")
#define DDR2_BL                     2

#define CEIL_DIV(numerator, denominator)  (((numerator) + (denominator) - 1) / (denominator))
#define MAX2(a, b)  ((a) > (b) ? (a) : (b))

// Upper time bound for any single DDR2 bring-up hardware wait. Every one of
// these (MPLL regulator/lock, host command issue, self-calibration) completes
// in well under a millisecond on healthy hardware; 100ms is a generous ceiling
// that still guarantees boot proceeds if a stage never completes.
#define DDR2_SPIN_TIMEOUT_US    100000u

// Busy-wait until `condition` is true, giving up after DDR2_SPIN_TIMEOUT_US
// using the CP0 core timer (same time base as ddr2DelayNanoseconds). Sets the
// bool `success_result` to true if the condition was met, false on timeout, so
// callers can flag the failing stage and let main() keep booting instead of
// hanging forever.
#define DDR2_WAIT_UNTIL(condition, success_result)                             \
    do {                                                                       \
        uint32_t _ns_per_tick = 2000000000u / SYSCLK_INT;                      \
        uint32_t _timeout_ticks =                                              \
            ((uint32_t)DDR2_SPIN_TIMEOUT_US * 1000u) / _ns_per_tick;           \
        uint32_t _wait_start = _CP0_GET_COUNT();                               \
        (success_result) = true;                                               \
        while (!(condition)) {                                                 \
            if ((uint32_t)(_CP0_GET_COUNT() - _wait_start) >= _timeout_ticks) {\
                (success_result) = false;                                      \
                break;                                                         \
            }                                                                  \
        }                                                                      \
    } while (0)

// ---- Delay register fields, PIC32 FRM Table 55-4 formulas ----
#define DDR2_REFDLY         (CEIL_DIV(DDR2_TRFC_NS, DDR2_CTL_CLK_PERIOD_NS) - 1)
#define DDR2_W2PCHRGDLY     (CEIL_DIV(DDR2_TWR_NS, DDR2_CTL_CLK_PERIOD_NS) + DDR2_WRITE_LATENCY + DDR2_BL)
#define DDR2_PCHRGALLDLY    (CEIL_DIV(DDR2_TRP_NS, DDR2_CTL_CLK_PERIOD_NS))
#define DDR2_PCHRG2RASDLY   (CEIL_DIV(DDR2_TRP_NS, DDR2_CTL_CLK_PERIOD_NS) - 1)
#define DDR2_RAS2CASDLY     (CEIL_DIV(DDR2_TRCD_NS, DDR2_CTL_CLK_PERIOD_NS) - 1)
#define DDR2_RAS2RASDLY     (CEIL_DIV(DDR2_TRRD_NS, DDR2_CTL_CLK_PERIOD_NS) - 1)
#define DDR2_W2RDLY         (CEIL_DIV(DDR2_TWTR_NS, DDR2_CTL_CLK_PERIOD_NS) + DDR2_WRITE_LATENCY + DDR2_BL)
#define DDR2_W2RCSDLY       MAX2(DDR2_W2RDLY - 1, 3)
#define DDR2_R2PCHRGDLY     (CEIL_DIV(DDR2_TRTP_NS, DDR2_CTL_CLK_PERIOD_NS) + DDR2_BL - 2)
#define DDR2_SLFREFEXDLY    ((DDR2_TDLLK_DRAM_CLKS / 2) - 2)
#define DDR2_RAS2PCHRGDLY   (CEIL_DIV(DDR2_TRAS_NS, DDR2_CTL_CLK_PERIOD_NS) - 1)
#define DDR2_RAS2RASSBNKDLY (CEIL_DIV(DDR2_TRC_NS, DDR2_CTL_CLK_PERIOD_NS) - 1)
#define DDR2_FAWTDLY        (CEIL_DIV(DDR2_TFAW_NS, DDR2_CTL_CLK_PERIOD_NS) - 1)
#define DDR2_RMWDLY         (DDR2_READ_LATENCY - DDR2_WRITE_LATENCY + 3)
#define DDR2_R2WDLY         (DDR2_BL + 2)
#define DDR2_W2WCSDLY       (DDR2_BL - 1)
#define DDR2_W2WDLY         (DDR2_BL - 1)
#define DDR2_R2RCSDLY       (DDR2_BL)
#define DDR2_R2RDLY         (DDR2_BL - 1)
#define DDR2_RBENDDLY       (DDR2_READ_LATENCY + 3)
#define DDR2_NXTDATRQDLY    (DDR2_WRITE_LATENCY - 2)
#define DDR2_NXTDATAVDLY    (DDR2_READ_LATENCY + 4)
#define DDR2_RDATENDLY      (DDR2_READ_LATENCY - 2)
#define DDR2_REFCNT         (CEIL_DIV(DDR2_TREFI_NS, DDR2_CTL_CLK_PERIOD_NS) - 2)

// tCKE/tXP are given in DRAM-clock cycles (ntCK) in the data sheet, but
// these two FRM formulas operate in the controller-clock domain -- convert
// through nanoseconds so the /CTL_CLK_PERIOD_NS division is meaningful
#define DDR2_TCKE_NS        (DDR2_TCKE_DRAM_CLKS * DDR2_TCK_NS)
#define DDR2_TXP_NS         (DDR2_TXP_DRAM_CLKS * DDR2_TCK_NS)
#define DDR2_PWRDNMINDLY    (CEIL_DIV(DDR2_TCKE_NS, DDR2_CTL_CLK_PERIOD_NS) - 1)
#define DDR2_SLFREFMINDLY   (CEIL_DIV(DDR2_TCKE_NS, DDR2_CTL_CLK_PERIOD_NS) - 1)
#define DDR2_PWRDNEXDLY     MAX2((CEIL_DIV(DDR2_TXP_NS, DDR2_CTL_CLK_PERIOD_NS) - 1), DDR2_SLFREFMINDLY)

// Minimum wait between Load Mode commands (tMRD), with a small fixed floor
// since the raw formula (1 controller clock) leaves no margin and this
// only runs once at boot
#define DDR2_MRS_WAIT       MAX2(CEIL_DIV(DDR2_TMRD_DRAM_CLKS * DDR2_TCK_NS, DDR2_CTL_CLK_PERIOD_NS), 4)

// ---- JEDEC DDR2 Mode Register (MR) fields (JESD79-2F; identical across
// every DDR2 vendor's datasheet, e.g. Micron's 256Mb DDR2 "Mode Register
// (MR) Definition") ----
#define DDR2_MR_BURST_LENGTH_8      (0x3u << 0)   // M0-M2 = 011
#define DDR2_MR_BURST_TYPE_SEQ      (0x0u << 3)   // M3 = 0 (sequential)
#define DDR2_MR_CAS_LATENCY_3       (0x3u << 4)   // M4-M6 = 011 (CL = 3)
#define DDR2_MR_DLL_RESET           (0x1u << 8)   // M8 = 1 (self-clearing)
// WR = ceil(tWR / tCK) = ceil(15ns / 5ns) = 3 clocks -> code 010
#define DDR2_MR_WRITE_RECOVERY_3    (0x2u << 9)   // M9-M11 = 010
#define DDR2_MR_BASE  (DDR2_MR_BURST_LENGTH_8 | DDR2_MR_BURST_TYPE_SEQ | \
                        DDR2_MR_CAS_LATENCY_3 | DDR2_MR_WRITE_RECOVERY_3)
#define DDR2_MR_VALUE            (DDR2_MR_BASE)
#define DDR2_MR_VALUE_DLL_RESET  (DDR2_MR_BASE | DDR2_MR_DLL_RESET)

// ---- JEDEC DDR2 Extended Mode Register (EMR/EMR1) fields ----
#define DDR2_EMR_DLL_ENABLE   (0x0u << 0)   // E0 = 0
#define DDR2_EMR_DRIVE_FULL   (0x0u << 1)   // E1 = 0 (full strength)
#define DDR2_EMR_RTT_DISABLED (0x0u)        // E2 = 0, E6 = 0 -- ODT unused, see ddr2ControllerConfigure()
#define DDR2_EMR_AL_0         (0x0u << 3)   // E3-E5 = 0 (posted CAS additive latency unused)
#define DDR2_EMR_OCD_EXIT     (0x0u << 7)   // E7-E9 = 000
#define DDR2_EMR_OCD_DEFAULT  (0x7u << 7)   // E7-E9 = 111
#define DDR2_EMR_BASE  (DDR2_EMR_DLL_ENABLE | DDR2_EMR_DRIVE_FULL | DDR2_EMR_RTT_DISABLED | DDR2_EMR_AL_0)
#define DDR2_EMR_VALUE             (DDR2_EMR_BASE | DDR2_EMR_OCD_EXIT)
#define DDR2_EMR_VALUE_OCD_DEFAULT (DDR2_EMR_BASE | DDR2_EMR_OCD_DEFAULT)

// EMR2/EMR3: all bits reserved on this part except EMR2 bit A7 (high-
// temperature self-refresh rate, left at its commercial/0 default here)
#define DDR2_EMR2_VALUE   0x0000
#define DDR2_EMR3_VALUE   0x0000

// Bank address (BA2:BA0) selecting which register a Load Mode command targets
#define DDR2_BANK_MR     0x0
#define DDR2_BANK_EMR    0x1
#define DDR2_BANK_EMR2   0x2
#define DDR2_BANK_EMR3   0x3

// Address bit A10 = 1 selects "all banks" for a Precharge command
#define DDR2_PRECHARGE_ALL_ADDR   (1u << 10)

// One entry in the JEDEC initialization command table (PIC32 FRM 55.5.1,
// Table 55-6). "ras"/"cas"/"we" are the first-cycle command truth table
// values; the second/subsequent cycle is always CKE-high/all-deselected
// per Table 55-6, so it isn't tracked per command here.
typedef struct {
    uint8_t  ras, cas, we;
    uint8_t  cs_active;    // 1 if CS0 is driven low (selected) for this command
    uint8_t  bank;         // BNKADDRCMD<2:0>
    uint16_t address;      // MDALCMD<7:0> / MDADDRHCMD<7:0>, split when packed
    uint16_t wait_cycles;  // controller clocks to hold before the next command
} ddr2_init_command_t;

static const ddr2_init_command_t ddr2_init_sequence[] = {

    // a) Bring CKE high, hold for the mandatory >=400ns post-reset delay
    { 1, 1, 1, 0, 0, 0,
      CEIL_DIV(400, DDR2_CTL_CLK_PERIOD_NS) },

    // b) Precharge all banks
    { 0, 1, 0, 1, 0, DDR2_PRECHARGE_ALL_ADDR,
      DDR2_PCHRGALLDLY },

    // c) EMR2 (commercial default)
    { 0, 0, 0, 1, DDR2_BANK_EMR2, DDR2_EMR2_VALUE,
      DDR2_MRS_WAIT },

    // d) EMR3 (all reserved)
    { 0, 0, 0, 1, DDR2_BANK_EMR3, DDR2_EMR3_VALUE,
      DDR2_MRS_WAIT },

    // e) EMR: enable DLL
    { 0, 0, 0, 1, DDR2_BANK_EMR, DDR2_EMR_VALUE,
      DDR2_MRS_WAIT },

    // f) MR: reset DLL. 200 DRAM clocks (100 controller clocks at half
    // rate) must elapse before the DLL may be trusted for a READ; held here
    // rather than split across the steps in between.
    { 0, 0, 0, 1, DDR2_BANK_MR, DDR2_MR_VALUE_DLL_RESET,
      (DDR2_TDLLK_DRAM_CLKS / 2) },

    // g) Precharge all banks
    { 0, 1, 0, 1, 0, DDR2_PRECHARGE_ALL_ADDR,
      DDR2_PCHRGALLDLY },

    // h) Two auto-refresh commands, tRFC apart
    { 0, 0, 1, 1, 0, 0,
      CEIL_DIV(DDR2_TRFC_NS, DDR2_CTL_CLK_PERIOD_NS) },
    { 0, 0, 1, 1, 0, 0,
      CEIL_DIV(DDR2_TRFC_NS, DDR2_CTL_CLK_PERIOD_NS) },

    // i) MR again, DLL reset bit now cleared
    { 0, 0, 0, 1, DDR2_BANK_MR, DDR2_MR_VALUE,
      DDR2_MRS_WAIT },

    // j) EMR: OCD default state (all three OCD bits set)
    { 0, 0, 0, 1, DDR2_BANK_EMR, DDR2_EMR_VALUE_OCD_DEFAULT,
      DDR2_MRS_WAIT },

    // k) EMR: exit OCD calibration
    { 0, 0, 0, 1, DDR2_BANK_EMR, DDR2_EMR_VALUE,
      DDR2_MRS_WAIT },

};

#define DDR2_NUM_INIT_COMMANDS  (sizeof(ddr2_init_sequence) / sizeof(ddr2_init_sequence[0]))

static bool ddr2_ready = false;

// private function prototypes
static bool ddr2MPLLInitialize(void);
static void ddr2ControllerConfigure(void);
static void ddr2PHYConfigure(void);
static void ddr2LoadInitCommands(void);
static bool ddr2RunSelfCalibration(void);
static void ddr2DelayNanoseconds(uint32_t nanoseconds);

// This function starts the dedicated Memory PLL (MPLL) to clock the DDR2
// PHY at 200MHz, then runs the controller/PHY/SDRAM bring-up sequence.
// Blocks until the SDRAM is ready for normal reads/writes.
bool ddr2Initialize(void) {

    if (ddr2_ready) return true;

    // Each stage below flags the error handler and aborts (rather than
    // spinning forever) if its hardware wait times out, so a DDR2 bring-up
    // failure leaves ddr2_ready false and lets main() continue booting. The
    // specific flag identifies which stage failed -- inspect it with the
    // "Error Status?" / "Peripheral Status? DDR2" serial commands.
    bool wait_ok;

    if (!ddr2MPLLInitialize()) return false;

    // The DDR2 clock must be stable for >=200us before any initialization
    // command is issued (PIC32 FRM 55.5.1, step 1)
    ddr2DelayNanoseconds(200000);

    ddr2ControllerConfigure();
    ddr2PHYConfigure();
    ddr2LoadInitCommands();

    // Issue the loaded command table, then wait for hardware to clear
    // VALID once every command (and its individual inter-command wait) has
    // been transmitted (PIC32 FRM 55.5.1, steps 5-6)
    DDRMEMCONbits.STINIT = 1;
    DDR2_WAIT_UNTIL(DDRCMDISSUEbits.VALID == 0, wait_ok);
    if (!wait_ok) {

        error_handler.flags.DDR2_init_sequence_timeout = 1;
        return false;

    }

    // Enable the controller for normal operation (PIC32 FRM 55.5.1, step 7)
    DDRMEMCONbits.INITDN = 1;

    // Calibrate read-capture and write-alignment timing now that the SDRAM
    // can service the read/write bursts SCL uses internally to calibrate
    if (!ddr2RunSelfCalibration()) {

        error_handler.flags.DDR2_calibration_timeout = 1;
        return false;

    }

    ddr2_ready = true;

    return true;

}

// This function returns true once ddr2Initialize() has completed and the
// SDRAM is ready for normal reads/writes
bool ddr2IsReady(void) {

    return ddr2_ready && DDRMEMCONbits.INITDN;

}

// this function sets up the dedicated Memory PLL (MPLL) that clocks the
// DDR2 PHY, independent of SYSCLK/PBCLKx -- see the CFGMPLL bit
// descriptions in the PIC32MZ-DA family data sheet, Register 41-14
static bool ddr2MPLLInitialize(void) {

    bool wait_ok;

    deviceUnlock();

    // Divider/multiplier/output-divider must be set while the MPLL is
    // still disabled (its POR default state)
    CFGMPLLbits.MPLLIDIV  = DDR2_MPLL_INPUT_DIVIDER;
    CFGMPLLbits.MPLLMULT  = DDR2_MPLL_MULTIPLIER;
    CFGMPLLbits.MPLLODIV1 = DDR2_MPLL_OUTPUT_DIVIDER1;
    CFGMPLLbits.MPLLODIV2 = DDR2_MPLL_OUTPUT_DIVIDER2;

    // Disable the internal DDRVREF divider (INTVREFCON = 0b00). Silicon
    // erratum #21 (DS80000736, module DDR2C) states the internal DDRVREF
    // circuit is NON-FUNCTIONAL on this part: it must be left off and an
    // external resistor divider on the DDRVREF pin must supply VDDR1V8/2.
    // Enabling it (0b11) leaves the DDR2 PHY without a valid read reference,
    // so self-calibration (ddr2RunSelfCalibration) never passes and
    // ddr2Initialize() hangs.
    // NOTE: this requires an external VDDR1V8/2 divider on DDRVREF -- confirm
    // it is populated on the board, otherwise DDR2 will still not calibrate.
    CFGMPLLbits.INTVREFCON = 0b00;

    // Enable the MPLL voltage regulator, then the MPLL itself -- the
    // regulator must be ready before MPLLDIS is cleared
    CFGMPLLbits.MPLLVREGDIS = 0;
    DDR2_WAIT_UNTIL(CFGMPLLbits.MPLLVREGRDY != 0, wait_ok);
    if (!wait_ok) {

        deviceLock();
        error_handler.flags.DDR2_mpll_vreg_timeout = 1;
        return false;

    }

    CFGMPLLbits.MPLLDIS = 0;
    DDR2_WAIT_UNTIL(CFGMPLLbits.MPLLRDY != 0, wait_ok);
    if (!wait_ok) {

        deviceLock();
        error_handler.flags.DDR2_mpll_lock_timeout = 1;
        return false;

    }

    deviceLock();

    return true;

}

// this function configures DDR2 memory geometry, refresh, and AC timing
static void ddr2ControllerConfigure(void) {

    // ---- Address geometry: {CS, ROW, BA, COL}, matching this part's
    // 4,194,304 x 4 banks x 16-bit organization (13 row / 2 bank / 9 column
    // address bits, one Chip Select) -- PIC32 FRM Example 55-1 walks this
    // same geometry end to end ----
    DDRMEMCFG0bits.CLHADDR = 0;      // column address is not split
    DDRMEMCFG2 = 0x00000000;        // CLADDRHMSK = 0 (no high column field)
    DDRMEMCFG3 = 0x000001FF;        // CLADDRLMSK = 9 column bits

    DDRMEMCFG0bits.BNKADDR = 9;      // bank field shifted right by the column width (9)

    DDRMEMCFG0bits.RWADDR = 11;      // row field shifted right by column+bank width (9+2)
    DDRMEMCFG1 = 0x00001FFF;        // RWADDRMSK = 13 row bits

    DDRMEMCFG0bits.CSADDR = 24;      // CS field shifted right by column+bank+row width (9+2+13)

    // DDRMEMCFG4: BNKADDRMSK<2:0> at bits 2:0, CSADDRMSK<2:0> at bits 8:6
    // (PIC32 FRM Register 55-10) -- written directly rather than through
    // DDRMEMCFG4bits, whose auto-generated field widths do not match the
    // manual for this register (see the file header comment)
    DDRMEMCFG4 = (0x3u << 0)   // BNKADDRMSK: 2 bank address bits
                | (0x0u << 6); // CSADDRMSK: one Chip Select, no address bits needed

    // Auto-precharge every access: the simplest correct behavior for a
    // general store/read interface (no explicit page/bank management here,
    // at the cost of not keeping a row open across back-to-back accesses)
    DDRMEMCFG0bits.APCHRGEN = 1;

    // ---- Refresh ----
    DDRREFCFGbits.REFCNT  = DDR2_REFCNT;
    DDRREFCFGbits.REFDLY  = DDR2_REFDLY;
    DDRREFCFGbits.MAXREFS = 0x7;    // allow refreshes to queue rather than stall accesses

    // Auto power-down/self-refresh entry left disabled -- this driver does
    // not manage DDR2 power states
    DDRPWRCFG = 0x00000000;

    // ---- AC timing (PIC32 FRM Table 55-4 formulas, using this part's
    // DS60001565 Table 44-55 timing parameters, computed above) ----
    DDRDLYCFG0bits.W2RDLY   = DDR2_W2RDLY & 0xF;
    DDRDLYCFG0bits.W2RCSDLY = DDR2_W2RCSDLY & 0xF;
    DDRDLYCFG0bits.R2RDLY   = DDR2_R2RDLY;
    DDRDLYCFG0bits.R2RCSDLY = DDR2_R2RCSDLY;
    DDRDLYCFG0bits.W2WDLY   = DDR2_W2WDLY;
    DDRDLYCFG0bits.W2WCSDLY = DDR2_W2WCSDLY;
    DDRDLYCFG0bits.R2WDLY   = DDR2_R2WDLY;
    DDRDLYCFG0bits.RMWDLY   = DDR2_RMWDLY;

    DDRDLYCFG1bits.SLFREFMINDLY = DDR2_SLFREFMINDLY;
    DDRDLYCFG1bits.SLFREFEXDLY  = DDR2_SLFREFEXDLY & 0xFF;
    DDRDLYCFG1bits.SLFREFEXDLY8 = (DDR2_SLFREFEXDLY >> 8) & 0x1;
    DDRDLYCFG1bits.PWRDNMINDLY  = DDR2_PWRDNMINDLY;
    DDRDLYCFG1bits.PWRDNEXDLY   = DDR2_PWRDNEXDLY;
    DDRDLYCFG1bits.W2PCHRGDLY4  = (DDR2_W2PCHRGDLY >> 4) & 0x1;
    DDRDLYCFG1bits.W2RDLY4      = (DDR2_W2RDLY >> 4) & 0x1;
    DDRDLYCFG1bits.W2RCSDLY4    = (DDR2_W2RCSDLY >> 4) & 0x1;
    DDRDLYCFG1bits.NXTDATAVDLY4 = (DDR2_NXTDATAVDLY >> 4) & 0x1;

    DDRDLYCFG2bits.PCHRGALLDLY  = DDR2_PCHRGALLDLY;
    DDRDLYCFG2bits.R2PCHRGDLY   = DDR2_R2PCHRGDLY;
    DDRDLYCFG2bits.W2PCHRGDLY   = DDR2_W2PCHRGDLY & 0xF;
    DDRDLYCFG2bits.RAS2RASDLY   = DDR2_RAS2RASDLY;
    DDRDLYCFG2bits.RAS2CASDLY   = DDR2_RAS2CASDLY;
    DDRDLYCFG2bits.PCHRG2RASDLY = DDR2_PCHRG2RASDLY;
    DDRDLYCFG2bits.RBENDDLY     = DDR2_RBENDDLY;

    DDRDLYCFG3bits.RAS2PCHRGDLY   = DDR2_RAS2PCHRGDLY;
    DDRDLYCFG3bits.RAS2RASSBNKDLY = DDR2_RAS2RASSBNKDLY;
    DDRDLYCFG3bits.FAWTDLY        = DDR2_FAWTDLY;

    // ---- On-die termination: left disabled. The PIC32 FRM gives no
    // formula for ODT read/write delay-and-duration (unlike every other
    // DDRDLYCFGx field above), and with only one, in-package Chip Select on
    // very short internal traces, ODT is far less important than it would
    // be on an external SDRAM bus. Revisit (DDRODTCFG/DDRODTENCFG, PIC32
    // FRM Table 55-7/55-8) if signal integrity issues turn up in testing.
    DDRODTCFG = 0x00000000;
    DDRODTENCFG = 0x00000000;

    // ---- Transfer/burst configuration ----
    DDRXFERCFGbits.BIGENDIAN   = 0;   // MIPS32 little-endian in this project
    DDRXFERCFGbits.MAXBURST    = 1;   // conservative default; a performance tuning knob only
    DDRXFERCFGbits.NXTDATRQDLY = DDR2_NXTDATRQDLY;
    DDRXFERCFGbits.NXTDATAVDLY = DDR2_NXTDATAVDLY & 0xF;
    DDRXFERCFGbits.RDATENDLY   = DDR2_RDATENDLY;

    DDRMEMWIDTHbits.HALFRATE = 1;  // required -- this controller always runs in half-rate mode

}

// this function configures the DDR2 PHY: pad drive/ODT calibration, DLL,
// and PHY-side self-calibration (SCL) parameters. SCL itself is triggered
// separately, in ddr2RunSelfCalibration(), after the SDRAM is initialized.
static void ddr2PHYConfigure(void) {

    DDRPHYPADCONbits.HALFRATE   = 1;    // required, mirrors DDRMEMWIDTHbits.HALFRATE
    DDRPHYPADCONbits.NOEXTDLL   = 1;    // use the internal digital DLL; no external DLL populated
    DDRPHYPADCONbits.WRCMDDLY   = 1;    // required whenever WL (write latency) is even -- WL = 2 here
    DDRPHYPADCONbits.RCVREN     = 1;    // enable input receivers, needed for reads
    DDRPHYPADCONbits.PREAMBDLY  = 0b00; // 2-cycle write preamble (conservative default)
    // PHY I/O-pad on-die termination, ENABLED at 150 ohm per PIC32 FRM
    // Table 55-8. With the DRAM clock corrected to 200MHz, self-calibration
    // starts and engages phase calibration but stalls converging on a read-
    // capture point (DDRSCLSTART holds SCLPHCAL + internal status bits, pass
    // bits never set) -- the signature of an unterminated read eye. Enabling
    // read-side pad termination gives SCL a clean eye to lock onto. (This is
    // separate from the controller-scheduled DRAM Rtt in DDRODTCFG/
    // DDRODTENCFG, which remains off.)
    DDRPHYPADCONbits.ODTEN      = 1;    // ODT enabled (Table 55-8)
    DDRPHYPADCONbits.ODTSEL     = 1;    // 150 ohm termination (Table 55-8)
    DDRPHYPADCONbits.ODTPUCAL   = 0b10; // PIC32 FRM Table 55-8 calibration setting
    DDRPHYPADCONbits.ODTPDCAL   = 0b10; // PIC32 FRM Table 55-8 calibration setting
    // Pad drive strength: the PIC32 FRM gives no device-specific
    // recommendation for these; full drive / mid-range impedance trim are
    // reasonable starting points for bring-up, not derived values
    DDRPHYPADCONbits.ADDCDRVSEL = 1;
    DDRPHYPADCONbits.DATDRVSEL  = 1;
    DDRPHYPADCONbits.DRVSTRNFET = 0x8;
    DDRPHYPADCONbits.DRVSTRPFET = 0x8;

    // Digital DLL (PIC32 FRM Table 55-9 recommended settings)
    DDRPHYDLLRbits.DLYSTVAL   = 0x3;
    DDRPHYDLLRbits.DISRECALIB = 0;      // keep periodic recalibration on -- useful across this
                                        // project's operating temperature range
    DDRPHYDLLRbits.RECALIBCNT = 0x10;
    DDRPHYDLLCTRLbits.DDRDLLTRIM = 0x01;

    // Bypass the analog DLL in favor of the PHY's digital DLL (bit 24 of
    // DDRADLLBYP, PIC32 FRM Register 55-32), matching NOEXTDLL above
    DDRADLLBYP = (1u << 24);

    // Self-Calibration Logic (SCL) parameters (PIC32 FRM Table 55-7
    // recommended settings). Written as raw values per the manual's bit
    // positions -- see the file header comment.
    DDRSCLLAT = (4u << 4)                        // DDRCLKDLY: recommended value
              | (3u << 0);                       // CAPCLKDLY: recommended value
    DDRSCLCFG0 = (1u << 24)                       // ODTCSW: enabled during SCL writes
               | ((uint32_t)DDR2_CAS_LATENCY << 4) // RCASLAT: DRAM read CAS latency
               | (1u << 1)                        // DDR: DDR2 is connected
               | (1u << 0);                       // BURST8: required in half-rate mode
    DDRSCLCFG1 = (0u << 12)                       // DBLREFDLY: single delay (recommended)
               | ((uint32_t)DDR2_WRITE_LATENCY << 8) // WCASLAT: DRAM write CAS latency
               | (1u << 0);                       // SCLCSEN: run SCL on Chip Select 0
    DDRSCLCFG2 = 0b00;                            // SCLLANSEL: calibrate both byte lanes

    // SCL test address: row 0 / column 0 / bank 0 is always valid regardless
    // of geometry
    DDRPHYSCLADR = 0x00000000;

}

// this function loads the JEDEC DDR2 initialization command table
// (ddr2_init_sequence) into the DDRCMD1x/DDRCMD2x host command registers
static void ddr2LoadInitCommands(void) {

    // DDRCMD10..DDRCMD115 and DDRCMD20..DDRCMD215 are each 16 SFRs spaced 4
    // bytes apart in the device header -- addressed here as arrays via a
    // pointer to the first register in each block, rather than 16 separate
    // named assignments
    volatile uint32_t *ddrcmd1 = &DDRCMD10;
    volatile uint32_t *ddrcmd2 = &DDRCMD20;
    uint8_t i;

    for (i = 0; i < DDR2_NUM_INIT_COMMANDS; i++) {

        const ddr2_init_command_t *cmd = &ddr2_init_sequence[i];

        // Cycle 1 drives the actual command; cycle 2+ always reverts to
        // CKE high / all Chip Selects deselected (PIC32 FRM Table 55-6)
        uint32_t cs1 = cmd->cs_active ? 0xFEu : 0xFFu;

        // DDRCMD1x (PIC32 FRM Register 55-22)
        ddrcmd1[i] = (1u << 0)                         // CLKENCMD1
                   | (cs1 << 1)                         // CSCMD1<7:0>
                   | ((uint32_t)cmd->ras << 9)          // RASCMD1
                   | ((uint32_t)cmd->cas << 10)         // CASCMD1
                   | ((uint32_t)cmd->we  << 11)         // WENCMD1
                   | (1u << 12)                         // CLKENCMD2
                   | (0xFFu << 13)                      // CSCMD2<7:0> (deselected)
                   | (1u << 21) | (1u << 22) | (1u << 23) // RASCMD2/CASCMD2/WENCMD2 (deselected)
                   | (((uint32_t)cmd->address & 0xFFu) << 24); // MDALCMD<7:0>

        // DDRCMD2x (PIC32 FRM Register 55-23)
        ddrcmd2[i] = (((uint32_t)cmd->address >> 8) & 0xFFu)  // MDADDRHCMD<7:0>
                   | ((uint32_t)cmd->bank << 8)                // BNKADDRCMD<2:0>
                   | ((uint32_t)cmd->wait_cycles << 11);       // WAIT<8:0>

    }

    DDRCMDISSUEbits.NUMHOSTCMDS = DDR2_NUM_INIT_COMMANDS;
    DDRCMDISSUEbits.VALID = 1;

}

// this function triggers PHY self-calibration (read-capture and write-
// alignment timing) and blocks until both byte lanes report a pass
static bool ddr2RunSelfCalibration(void) {

    bool wait_ok;

    // Start self-calibration with SCLSTART (bit 28) only, per PIC32 FRM
    // (DS60001321) Register 55-24. SCLPHCAL (bit 29, phase calibration) is
    // deliberately NOT set: with SCLPHCAL enabled the SCL engages phase cal
    // but stalls (DDRSCLSTART holds bit 29 + an internal busy bit, CLKDLYDELTA
    // never sweeps, pass bits never assert). SCLSTART alone runs the normal
    // read-capture/write-alignment calibration. SCLEN (bit 26) stays clear --
    // that only enables dynamic/continuous recalibration ("may impact
    // performance"), not needed for one-time bring-up.
    DDRSCLSTART = (1u << 28);

    // Bits 1 (SCLUBPASS) and 0 (SCLLBPASS): upper/lower byte lane pass status
    DDR2_WAIT_UNTIL((DDRSCLSTART & 0x3u) == 0x3u, wait_ok);

    return wait_ok;

}

// this function busy-waits for at least the given number of nanoseconds,
// using the CPU core timer (CP0 Count, which increments at SYSCLK/2). Used
// instead of this project's generic softwareDelay() because DDR2 bring-up
// has hard minimum wait requirements (JESD79-2F) that an uncalibrated NOP
// loop cannot guarantee.
static void ddr2DelayNanoseconds(uint32_t nanoseconds) {

    const uint32_t ns_per_tick = 2000000000u / SYSCLK_INT;
    uint32_t ticks = CEIL_DIV(nanoseconds, ns_per_tick);
    uint32_t start = _CP0_GET_COUNT();

    while ((uint32_t)(_CP0_GET_COUNT() - start) < ticks);

}

// This function copies "length" bytes from DDR2 SDRAM starting at byte
// "offset" into "destination". Requests past the end of the 32MB are
// silently truncated to fit.
void ddr2Read(uint32_t offset, void *destination, uint32_t length) {

    if (offset >= DDR2_SIZE_BYTES) return;
    if (length > DDR2_SIZE_BYTES - offset) length = DDR2_SIZE_BYTES - offset;

    memcpy(destination, (const void *)(DDR2_KSEG1_BASE_ADDRESS + offset), length);

}

// This function copies "length" bytes from "source" into DDR2 SDRAM
// starting at byte "offset". Requests past the end of the 32MB are
// silently truncated to fit.
void ddr2Write(uint32_t offset, const void *source, uint32_t length) {

    if (offset >= DDR2_SIZE_BYTES) return;
    if (length > DDR2_SIZE_BYTES - offset) length = DDR2_SIZE_BYTES - offset;

    memcpy((void *)(DDR2_KSEG1_BASE_ADDRESS + offset), source, length);

}

// This function prints the DDR2 controller/PHY configuration and status
void printDDR2Status(void) {

    terminalTextAttributesReset();
    terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, BOLD_FONT);
    printf("DDR2 SDRAM Controller Status:\r\n");

    // ---- Overall readiness ----
    if (ddr2IsReady()) terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
    else terminalTextAttributes(RED_COLOR, BLACK_COLOR, NORMAL_FONT);
    printf("    Overall State: %s\r\n",
            ddr2IsReady() ? "Ready for reads/writes" : "NOT ready");

    // ---- Clocks and PLL ----
    // MFVCO = (POSC / MPLLIDIV) * MPLLMULT; DDR clock = MFVCO / (ODIV1 * ODIV2).
    // POSC is 24MHz on this board (external clock, POSCMOD=EC). These fields are
    // direct-encoded on this part (unlike the SYSPLL).
    const uint32_t posc_mhz = 24u;
    uint32_t mpll_idiv  = CFGMPLLbits.MPLLIDIV  ? CFGMPLLbits.MPLLIDIV  : 1;
    uint32_t mpll_mult  = CFGMPLLbits.MPLLMULT;
    uint32_t mpll_odiv1 = CFGMPLLbits.MPLLODIV1 ? CFGMPLLbits.MPLLODIV1 : 1;
    uint32_t mpll_odiv2 = CFGMPLLbits.MPLLODIV2 ? CFGMPLLbits.MPLLODIV2 : 1;
    uint32_t mpll_vco_mhz = (posc_mhz * mpll_mult) / mpll_idiv;
    uint32_t ddr_clk_mhz  = mpll_vco_mhz / (mpll_odiv1 * mpll_odiv2);

    terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, BOLD_FONT);
    printf("    Clocks and PLL:\r\n");

    if (CFGMPLLbits.MPLLRDY) terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
    else terminalTextAttributes(RED_COLOR, BLACK_COLOR, NORMAL_FONT);
    printf("        Memory PLL (MPLL): %s\r\n", CFGMPLLbits.MPLLRDY ? "Locked" : "Not Ready");

    if (CFGMPLLbits.MPLLVREGRDY) terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
    else terminalTextAttributes(RED_COLOR, BLACK_COLOR, NORMAL_FONT);
    printf("        MPLL Voltage Regulator: %s\r\n", CFGMPLLbits.MPLLVREGRDY ? "Ready" : "Not Ready");

    terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
    printf("        MPLL VCO: %u MHz (%u MHz POSC / %u x %u)\r\n", mpll_vco_mhz, posc_mhz, mpll_idiv, mpll_mult);
    printf("        DDR2 (DRAM) Clock: %u MHz (VCO / %u / %u)\r\n", ddr_clk_mhz, mpll_odiv1, mpll_odiv2);
    printf("        Controller Clock: %u MHz (half-rate, DRAM clock / 2)\r\n", ddr_clk_mhz / 2);
    printf("        Data Rate: %u MT/s (DDR, both clock edges)\r\n", ddr_clk_mhz * 2);

    // DDRVREF: the internal divider is non-functional on this silicon (erratum
    // #21). INTVREFCON must read 0 and an external divider must supply VDDR1V8/2.
    if (CFGMPLLbits.INTVREFCON == 0) terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
    else terminalTextAttributes(RED_COLOR, BLACK_COLOR, NORMAL_FONT);
    printf("        DDRVREF Source: %s (INTVREFCON=%u)\r\n",
            CFGMPLLbits.INTVREFCON == 0
                ? "External divider (internal disabled per erratum #21)"
                : "Internal (NON-FUNCTIONAL, see erratum #21)",
            (unsigned)CFGMPLLbits.INTVREFCON);

    // ---- Controller / operation ----
    terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, BOLD_FONT);
    printf("    Controller:\r\n");

    if (DDRMEMCONbits.INITDN) terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
    else terminalTextAttributes(RED_COLOR, BLACK_COLOR, NORMAL_FONT);
    printf("        Initialization: %s\r\n",
            DDRMEMCONbits.INITDN ? "Done (normal operation)" : "Not complete");

    if ((DDRSCLSTART & 0x3) == 0x3) terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
    else terminalTextAttributes(RED_COLOR, BLACK_COLOR, NORMAL_FONT);
    printf("        Self-Calibration (SCL): lower lane %s, upper lane %s\r\n",
            (DDRSCLSTART & 0x1) ? "Passed" : "Failed/Not Run",
            (DDRSCLSTART & 0x2) ? "Passed" : "Failed/Not Run");

    terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
    printf("        Transfer Mode: %s\r\n", DDRMEMWIDTHbits.HALFRATE ? "Half-rate" : "Full-rate");
    printf("        Auto-Precharge: %s\r\n",
            DDRMEMCFG0bits.APCHRGEN ? "Enabled (every access)" : "Disabled");
    // ---- On-Die Termination (ODT) detail ----
    // ODT is a two-step enable per PIC32 FRM 55.4.3: the PHY pad must have ODT
    // enabled (DDRPHYPADCON.ODTEN) AND the controller must assert it per
    // access (DDRODTENCFG.ODTREN for reads, .ODTWEN for writes, with start/
    // duration timing in DDRODTCFG). Pad-enabled but not controller-asserted
    // means no termination actually happens during the SCL read bursts.
    {
        unsigned odt_ren = (unsigned)(DDRODTENCFG & 0x1u);          // ODTREN  (read ODT assert)
        unsigned odt_wen = (unsigned)((DDRODTENCFG >> 16) & 0x1u);  // ODTWEN  (write ODT assert)
        unsigned odt_csw = (unsigned)((DDRSCLCFG0 >> 24) & 0x1u);   // ODTCSW  (ODT during SCL writes)

        terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, BOLD_FONT);
        printf("        On-Die Termination (ODT):\r\n");

        // PHY pad ODT enable + impedance
        if (DDRPHYPADCONbits.ODTEN) terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
        else terminalTextAttributes(RED_COLOR, BLACK_COLOR, NORMAL_FONT);
        printf("            PHY pad ODT (ODTEN): %s\r\n", DDRPHYPADCONbits.ODTEN ? "Enabled" : "Disabled");

        terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
        printf("            Termination (ODTSEL): %s\r\n", DDRPHYPADCONbits.ODTSEL ? "150 ohm" : "75 ohm");
        printf("            Pad cal (ODTPUCAL/ODTPDCAL): %u / %u\r\n",
                (unsigned)DDRPHYPADCONbits.ODTPUCAL, (unsigned)DDRPHYPADCONbits.ODTPDCAL);

        // Controller assertion -- the part that actually terminates a transfer.
        // Read ODT off is highlighted because SCL calibrates on read bursts.
        if (odt_ren) terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
        else terminalTextAttributes(RED_COLOR, BLACK_COLOR, NORMAL_FONT);
        printf("            Controller read ODT (ODTREN): %s\r\n", odt_ren ? "Asserted" : "NOT asserted");

        terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
        printf("            Controller write ODT (ODTWEN): %s\r\n", odt_wen ? "Asserted" : "Not asserted");
        printf("            ODT during SCL writes (ODTCSW): %s\r\n", odt_csw ? "Enabled" : "Disabled");
        printf("            DDRODTCFG=0x%08X  DDRODTENCFG=0x%08X\r\n",
                (unsigned)DDRODTCFG, (unsigned)DDRODTENCFG);
    }

    terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
    printf("        Data Endianness: %s\r\n",
            DDRXFERCFGbits.BIGENDIAN ? "Big-endian" : "Little-endian");

    // ---- Timing ----
    terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, BOLD_FONT);
    printf("    Timing:\r\n");
    terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
    printf("        CAS Latency (CL): %d, Read Latency (RL): %d, Write Latency (WL): %d\r\n",
            DDR2_CAS_LATENCY, DDR2_READ_LATENCY, DDR2_WRITE_LATENCY);
    printf("        Burst Length: 8\r\n");
    printf("        DRAM Period (tCK): %d ns, Controller Period: %d ns\r\n",
            DDR2_TCK_NS, DDR2_CTL_CLK_PERIOD_NS);
    printf("        Datasheet params (ns): tRCD %d, tRP %d, tRAS %d, tRC %d, tRFC %d, tWR %d\r\n",
            DDR2_TRCD_NS, DDR2_TRP_NS, DDR2_TRAS_NS, DDR2_TRC_NS, DDR2_TRFC_NS, DDR2_TWR_NS);
    printf("        Refresh Interval (tREFI): %d ns  [REFCNT=%u, REFDLY=%u, MAXREFS=%u]\r\n",
            DDR2_TREFI_NS, (unsigned)DDRREFCFGbits.REFCNT,
            (unsigned)DDRREFCFGbits.REFDLY, (unsigned)DDRREFCFGbits.MAXREFS);

    // ---- Geometry / capacity / address map ----
    terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, BOLD_FONT);
    printf("    Geometry and Address Map:\r\n");
    terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
    printf("        Organization: 13 row / 2 bank / 9 column bits, 16-bit data, 1 chip select\r\n");
    printf("        Capacity: 32 MB (4,194,304 locations x 4 banks x 16 bits)\r\n");
    printf("        Physical: 0x%08X   KSEG0 (cached): 0x%08X   KSEG1 (uncached): 0x%08X\r\n",
            DDR2_PHYSICAL_BASE_ADDRESS, DDR2_KSEG0_BASE_ADDRESS, DDR2_KSEG1_BASE_ADDRESS);

    // ---- Raw register snapshot (for bring-up debugging) ----
    terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, BOLD_FONT);
    printf("    Raw Registers:\r\n");
    terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
    printf("        CFGMPLL=0x%08X  DDRMEMCON=0x%08X  DDRSCLSTART=0x%08X\r\n",
            (unsigned)CFGMPLL, (unsigned)DDRMEMCON, (unsigned)DDRSCLSTART);
    printf("        DDRMEMCFG0=0x%08X  DDRREFCFG=0x%08X  DDRXFERCFG=0x%08X\r\n",
            (unsigned)DDRMEMCFG0, (unsigned)DDRREFCFG, (unsigned)DDRXFERCFG);
    printf("        DDRDLYCFG 0=0x%08X 1=0x%08X 2=0x%08X 3=0x%08X\r\n",
            (unsigned)DDRDLYCFG0, (unsigned)DDRDLYCFG1, (unsigned)DDRDLYCFG2, (unsigned)DDRDLYCFG3);
    printf("        DDRPHYPADCON=0x%08X\r\n", (unsigned)DDRPHYPADCON);
    // SCL block + read-capture DLL registers, for self-calibration debugging.
    // DDRPHYCLKDLY mirrors the SCL pass status (bits 4:3) and holds the SCL-
    // computed capture delta in CLKDLYDELTA (bits 2:0); a railed 0x7 delta
    // with pass bits 0 means SCL swept the whole range without a valid eye.
    printf("        DDRSCLLAT=0x%08X  DDRSCLCFG0=0x%08X  DDRSCLCFG1=0x%08X\r\n",
            (unsigned)DDRSCLLAT, (unsigned)DDRSCLCFG0, (unsigned)DDRSCLCFG1);
    printf("        DDRPHYDLLR=0x%08X  DDRADLLBYP=0x%08X  DDRPHYCLKDLY=0x%08X\r\n",
            (unsigned)DDRPHYDLLR, (unsigned)DDRADLLBYP, (unsigned)DDRPHYCLKDLY);

    // ---- Bring-up error flags ----
    terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, BOLD_FONT);
    printf("    Bring-up Errors:\r\n");

    if (error_handler.flags.DDR2_mpll_vreg_timeout ||
            error_handler.flags.DDR2_mpll_lock_timeout ||
            error_handler.flags.DDR2_init_sequence_timeout ||
            error_handler.flags.DDR2_calibration_timeout) {

        terminalTextAttributes(RED_COLOR, BLACK_COLOR, NORMAL_FONT);
        if (error_handler.flags.DDR2_mpll_vreg_timeout)
            printf("        MPLL voltage regulator ready timeout\r\n");
        if (error_handler.flags.DDR2_mpll_lock_timeout)
            printf("        MPLL lock timeout\r\n");
        if (error_handler.flags.DDR2_init_sequence_timeout)
            printf("        Init command sequence timeout\r\n");
        if (error_handler.flags.DDR2_calibration_timeout)
            printf("        Self-calibration timeout\r\n");

    }

    else {

        terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
        printf("        None\r\n");

    }

    terminalTextAttributesReset();

}

/* *****************************************************************************
 End of File
 */
