/*******************************************************************************
  FLIR Lepton VoSPI (Video over SPI) Capture Driver

  File Name:
    flir_vospi.c

  Summary:
    SPI4 + DMA capture and frame assembly for the Lepton 3.5. See flir_vospi.h
    for the VoSPI framing and the two-channel DMA capture design.
*******************************************************************************/

#include "application/flir/flir_vospi.h"
#include "core/device_control.h"
#include "core/32mzda_interrupt_control.h"
#include "gpio/pin_macros.h"
#include "usb_uart/terminal_control.h"

#include <xc.h>
#include <sys/kmem.h>
#include <sys/attribs.h>
#include <stdio.h>
#include <string.h>

// SPI4 is clocked from PBCLK2 (SYSCLK/3 = 66.67 MHz), same as SPI3 (spi3.c).
#define FLIR_VOSPI_PBCLK_HZ         (SYSCLK_INT / 3u)

// VoSPI clock. (Fsck = PBCLK/(2*(BRG+1)).) BRG=3 gives PBCLK2 / 8 = 8.33 MHz.
//
// This started at BRG=1 (16.67 MHz) on the "well under the Lepton's ~20 MHz
// limit" argument, which was the wrong thing to size against. The binding
// constraint is the RX DMA, not the sensor: at 16.67 MHz a byte lands every
// 32 PBCLK2 cycles, and that channel is competing for the bus with the GLCD
// scanning its framebuffer out of DDR2, LVGL drawing into it, and USB. Fall
// behind by a single byte and the block never completes (see
// FLIR_VOSPI_DEADLOCK_MS). 8.33 MHz doubles the service window per byte.
//
// There is throughput to spare: a segment is 60 packets = ~9.4ms of clocking
// here, so a whole 4-segment frame reads in ~38ms against a 115ms frame
// period -- 3x margin. Even 4.17 MHz (BRG=7) would work if this proves to
// still be too tight.
#define FLIR_VOSPI_BRG              3u

// DMA channels: DCH3 generates the clock (dummy TX), DCH2 captures RX. DMA
// channels 0/1 are the USB UART (usb_uart.h); 2/3 are otherwise free.
// Interrupt priorities: DMA at IPL5, VSYNC/INT1 at IPL4 -- both have their own
// shadow register set (PRISS, interruptControllerInitialize()) and sit clear
// of I2C (IPL7) and the USB UART (IPL1/2).
#define FLIR_VOSPI_DMA_IPL          5
#define FLIR_VOSPI_VSYNC_IPL        4

// --- Gapless capture via hardware channel chaining ---------------------------
// Bench-validated 2026-07-29: chained capture works and measured a little more
// stable than the software re-arm, so 1 is the running configuration. The
// legacy (0) path is kept as the fallback.
//
// In the proven (0) configuration the sensor's clock STOPS at every block
// boundary: the TX channel runs out of dummy bytes when its block completes,
// and nothing restarts it until the DMA ISR runs FLIR_VOSPI_ArmBlock(). Every
// block boundary is therefore a bet on ISR entry latency -- if an I2C
// telemetry burst (IPL7, above this driver's IPL5) or any interrupt-masked
// window lands there, the clock pause stretches and the sensor can abandon
// the segment (block-boundary desyncs measured ~18x over-represented before
// the ping-pong shrank the gap; what remains of the gap IS the ISR entry
// latency). One abandoned segment costs at least one whole ~115ms frame -- a
// visible hitch in the video.
//
// With chaining (1), the re-arm leaves software entirely. Two RX channels
// (DCH2/DCH3, one per ping-pong block) are cross-chained so the DMA
// controller enables each one's partner in the same cycle its own block
// completes. The TX side is a SINGLE channel (DCH4) with CHAEN, continuously
// enabled: it just wraps its dummy block forever, so there is no TX hand-off
// to fail. (This replaced a cross-chained TX pair whose recovery statistics
// looked like TX hand-off stalls -- bench 2026-07-29, 93 clock stops in
// ~33s; the change cut the stall rate ~7x. NOTE: "zero RX overflows" is NOT
// proof the RX side is healthy -- as an enhanced-buffer master this SPI
// pauses instead of overflowing when its RX FIFO fills, so an RX-side wedge
// also presents as a stopped clock; see FLIR_VOSPI_UnstickClock() for how
// the two are told apart and repaired in place.) The ISR's only job is
// parsing a completed block, with a whole block time (~9.4ms) of deadline
// instead of microseconds. DCH5 is free again.
#define FLIR_VOSPI_USE_CHAINED_DMA  1

// A discard/idle packet has 0xF in the ID word's top nibble.
#define FLIR_VOSPI_IS_DISCARD(hdr0) (((hdr0) & 0x0Fu) == 0x0Fu)

// CP0 Count runs at SYSCLK/2 (same basis as flir.c).
#define FLIR_VOSPI_TICKS_PER_MS     ((uint32_t)(SYSCLK_INT / 2u) / 1000u)

// *** The VoSPI re-synchronization rule, and why the first version of this
// driver could never recover from a desync ***
//
// Everything the host reads is a byte stream: SCK is generated by us, and the
// Lepton simply shifts out whatever comes next. The 164-byte packet boundary
// is therefore decided entirely by where we START clocking -- if the first
// captured byte is not a packet's first header byte, EVERY subsequent 164-byte
// DMA block is the same rotated view of the stream, forever. Nothing in the
// data recovers it, because the sensor never inserts a gap to re-align to; the
// packet-number check just fails over and over (desyncCount climbing by
// thousands with frames=0 is exactly this).
//
// Per the Lepton engineering datasheet the only cure is to make the sensor
// itself restart its stream: de-assert /CS and keep the clock idle for at
// least 5 frame periods (~185ms), after which the next /CS assertion begins on
// a packet boundary. So a desync now disarms the DMA and schedules that idle
// window (FLIR_VOSPI_Tasks re-arms when it expires) instead of re-arming
// immediately.
#define FLIR_VOSPI_RESYNC_IDLE_MS   200u

// Deadlock detector. If the RX DMA ends up even one byte short of its block --
// a lost RX event, a byte dropped under bus contention -- the block never
// completes, and because our TX DMA has already finished its dummy bytes there
// are no more clocks coming to feed it. Capture then sits silently armed
// forever with no error flag anywhere: no SPIROV (nothing overflowed), no
// desync (no packet completed). That is the "frames=0, no errors, last packet
// N ms ago" signature. A block is ~9.4ms of clocking at 8.33MHz, so this is
// ~10 block times.
//
// NOTE: in chained mode this detector is effectively inert -- the clock never
// stops, so blocks keep completing and lastPacketTicks keeps being petted no
// matter how wrong things are. It stays only as a catch-all for the SPI/DMA
// dying outright; every real chained-mode failure is caught by the stall
// watchdog and the parser-level guards below instead.
#define FLIR_VOSPI_DEADLOCK_MS      100u

// If no packet is accepted for this long, capture is hunting a packet 0 that
// misalignment will never produce (or the stream has stopped) -- same cure
// either way: the /CS window.
//
// The two modes earn very different numbers. In legacy mode the clock stops
// between blocks and recovery hiccups can legitimately run long, so 1500ms
// (~13 frames) keeps the watchdog from livelocking a resync in progress. In
// chained mode the clock is gapless: packet 0s keep arriving every 60 packets
// (~9.4ms), so after any transient the parser re-locks within about one
// segment, and 300ms (~10 segment periods with zero accepted packets) is
// already overwhelming proof of real misalignment. Waiting 1500ms there just
// stretched every hard failure into a ~1.7s freeze -- the single biggest
// stability regression against the first-working build.
#if FLIR_VOSPI_USE_CHAINED_DMA
#define FLIR_VOSPI_STALL_TIMEOUT_MS 300u
#else
#define FLIR_VOSPI_STALL_TIMEOUT_MS 1500u
#endif

// Packet-sequence breaks with no complete segment in between before the grid
// is declared genuinely misaligned and the /CS window is paid for. A healthy
// stream sees isolated breaks (the sensor abandoning a segment) with complete
// segments between them; a run of breaks back to back only happens when byte
// alignment is actually lost. This catches misalignment in ~8 block times
// where the stall watchdog alone can be strung along much longer by false
// packet-0 locks that pet it.
#define FLIR_VOSPI_MAX_DESYNC_RUN   8u

// Consecutive wholly-blank blocks before the line is declared dead and the
// /CS window is taken. Not 1: the sensor does not necessarily drive MISO the
// instant /CS asserts after a resync, and reacting to the very first blank
// block made recovery chase its own tail (resync -> blank first block ->
// resync -> ...). Three blocks is ~28ms -- far longer than any start-up
// delay, still well inside one frame period.
#define FLIR_VOSPI_BLANK_BLOCK_RUN  3u

// Chained-mode clock unstick. Blocks complete every ~9.4ms by hardware alone,
// so "no packet for 2+ block times" can only mean the byte flow has stopped.
// FLIR_VOSPI_UnstickClock() diagnoses which side wedged and recovers in
// place, without the 200ms /CS window -- a ~20ms blip instead of a ~300ms+
// freeze. If a few recoveries in a row buy no packets, something deeper is
// wrong and the /CS window is taken after all.
#define FLIR_VOSPI_UNSTICK_MS       20u
#define FLIR_VOSPI_MAX_UNSTICKS     3u

// Bound on waiting for a forced RX DMA cell (CFORCE) to complete inside the
// unstick path -- a couple of bus transactions, so 10us is generous.
#define FLIR_VOSPI_CFORCE_TIMEOUT_TICKS  (FLIR_VOSPI_TICKS_PER_MS / 100u)

// --- Capture buffers -------------------------------------------------------

// Two blocks, ping-ponged: the ISR points the DMA at the far buffer and
// re-arms BEFORE it parses the one that just filled, so the clock restarts
// within a few hundred nanoseconds instead of pausing for the length of the
// parse. That gap matters -- with a single buffer, desyncs at a block boundary
// ran ~18x over-represented against breaks elsewhere in the stream (25 of 83,
// where an even spread predicts ~1.4), i.e. stopping the clock mid-segment was
// itself making the sensor abandon segments. Coherent (uncached) so the CPU
// sees exactly what DMA wrote, and word-aligned for the DMA engine.
static uint8_t vospiBlock[2][FLIR_VOSPI_BLOCK_BYTES] __attribute__((coherent, aligned(4)));

#if !FLIR_VOSPI_USE_CHAINED_DMA
// Which of the two blocks the DMA is currently filling. (In chained mode the
// buffer choice is fixed per channel -- DCH2 fills block 0, DCH3 block 1 --
// so no software bookkeeping exists to get out of step.)
static volatile uint8_t activeBlock;
#endif

// Zero bytes clocked out to drive SCK for one block. Not const: the DMA engine
// reads it from RAM, and 'coherent' (uncached DMA memory) is incompatible with
// the .rodata section 'const' would place it in. Never written, so it stays
// all-zero (static zero-initialization). SDO4 goes nowhere the sensor listens,
// so the content is irrelevant -- only the clocks it generates matter.
static uint8_t vospiTxDummy[FLIR_VOSPI_BLOCK_BYTES] __attribute__((coherent, aligned(4)));

// One segment's raw payloads accumulate here (CPU-only, no DMA) until the
// segment completes and is placed into the frame buffer.
static uint8_t segScratch[FLIR_VOSPI_PACKETS_PER_SEGMENT * FLIR_VOSPI_PACKET_PAYLOAD_BYTES];

// Two DDR2 frame buffers (14-bit values). captureFrame is being filled;
// readyFrame is the last completed one handed to the app.
static volatile uint16_t *captureFrame;
static volatile uint16_t *readyFrame;
static volatile bool frameReadyFlag;

// --- Capture state machine (all touched only in the DMA ISR) ---------------
static bool     haveSync;         // locked onto the packet-0..59 sequence
static uint8_t  expectedPacket;   // next packet number we expect (0..59)
static uint8_t  currentSegment;   // segment id from packet 20 (1..4)
static uint8_t  segmentMask;      // bitmask of segments placed for this frame
static uint32_t packetRun;        // current unbroken in-sequence packet count
static uint32_t consecutiveDesyncs; // sequence breaks since the last complete
                                    // segment -- NOT reset by ResetSync(), so
                                    // it can count across the soft re-hunts
                                    // that misalignment churns through
static uint8_t  blankBlockRun;      // consecutive wholly-blank blocks
static volatile uint8_t consecutiveUnsticks; // clock restarts since the last
                                             // completed block (Tasks bumps
                                             // it, any RX ISR clears it)
static FLIR_VOSPI_STATS stats;

// --- Packet dump ring (diagnostics) ----------------------------------------
// The leading bytes of the last few packets the DMA delivered, whatever they
// were. Written unconditionally at the top of the ISR so it also captures the
// cases the parser throws away (discards, misaligned windows).
static uint8_t dumpRing[FLIR_VOSPI_DUMP_PACKETS][FLIR_VOSPI_DUMP_BYTES];
static volatile uint8_t dumpNext;

// --- Capture arming / re-synchronization (ISR + thread context) ------------
static volatile bool     captureRunning;    // CS asserted, DMA armed
static volatile bool     capturePending;    // waiting out the /CS idle window
static volatile uint32_t csIdleStartTicks;  // CP0 Count when /CS went high
static volatile uint32_t lastProgressTicks; // CP0 Count of the last good packet
static volatile uint32_t lastPacketTicks;   // CP0 Count of the last packet of
                                            // ANY kind -- distinguishes "the
                                            // stream stopped" from "the stream
                                            // is running but never locks"

// Reset the frame-assembly state (called on start and on any desync).
static void FLIR_VOSPI_ResetSync(void)
{
    haveSync = false;
    expectedPacket = 0;
    currentSegment = 0;
    segmentMask = 0;
    packetRun = 0;
}

// CP0 ticks elapsed since an ISR-maintained timestamp. The ORDER of the two
// reads is the whole point: the stamp is read FIRST, so an ISR updating it
// mid-calculation can only make the next call's result smaller -- never
// negative. The previous pattern (capture CP0 'now' at the top of Tasks,
// compare stamps against it later) had it backwards: an ISR stamping between
// the CP0 read and the comparison left stamp > now, the unsigned subtraction
// wrapped to ~43 seconds, and the watchdog fired on a perfectly healthy
// stream -- a spurious TX abort or a spurious 200ms resync each time.
static inline uint32_t FLIR_VOSPI_TicksSince(volatile const uint32_t *stamp)
{
    uint32_t s = *stamp;
    return (uint32_t)(_CP0_GET_COUNT() - s);
}

void FLIR_VOSPI_Initialize(void)
{
    // --- SPI4 (mirrors spi3.c, but VoSPI is SPI mode 3 and read-mostly) ---
    SPI4CONbits.ON = 0;
    SPI4STATbits.SPIROV = 0;
    (void)SPI4BUF;

    SPI4BRG = FLIR_VOSPI_BRG;

    SPI4CONbits.MSTEN = 1;      // master: we generate the clock for the slave
    SPI4CONbits.SIDL = 0;

    // SPI mode 3 for VoSPI: clock idles high, data sampled on the rising
    // (idle-to-active) edge. PIC32's CKE is inverted vs CPHA, so mode 3 is
    // CKP=1 / CKE=0.
    SPI4CONbits.CKP = 1;
    SPI4CONbits.CKE = 0;
    SPI4CONbits.SMP = 1;        // sample input at the end of the output time

    SPI4CONbits.MODE32 = 0;     // 8-bit words
    SPI4CONbits.MODE16 = 0;

    SPI4CONbits.SSEN = 0;       // CS is a plain GPIO (nFLIR_VOSPI_CS), not SS
    SPI4CONbits.MSSEN = 0;
    SPI4CONbits.MCLKSEL = 0;    // PBCLK, not REFCLK
    SPI4CONbits.FRMEN = 0;

    // Enhanced (FIFO) buffer mode with interrupts that pace the DMA.
    SPI4CONbits.ENHBUF = 1;

    // TX event: buffer NOT FULL (0b11), so the DMA is invited to top the FIFO
    // up whenever there is any room and runs up to 16 bytes ahead of the
    // shifter.
    //
    // This was 0b01, which the comment here called "buffer not full" but which
    // the ATDF says is "buffer completely empty" (0b11 is not-full; the header
    // bitfield names are no help, cf. the DDR2 lesson). The difference is the
    // whole bug: with 0b01 the DMA was woken only once the 16-byte FIFO had
    // drained to nothing, then wrote a single byte (CSIZ=1), which left the
    // FIFO non-empty so no further event came until it drained again. The
    // transmitter therefore ran with a one-byte pipeline and NO latency slack
    // at all -- any delay servicing that event stopped the clock mid-packet,
    // making the sensor abort the segment (every bench-observed stall was a TX
    // stall, 26 of 26). Not-full gives the DMA ~16 byte-times (~15us at
    // 8.33MHz) of slack instead of ~0.
    SPI4CONbits.STXISEL = 0b11;

    // RX event: buffer not empty (0b01 per the same table) -- correct as-is;
    // the RX channel wants to drain the FIFO as eagerly as possible.
    SPI4CONbits.SRXISEL = 0b01;

    SPI4CONbits.ON = 1;

    // --- DMA controller ---
    DMACONbits.ON = 1;          // idempotent; also enabled by the USB UART

#if FLIR_VOSPI_USE_CHAINED_DMA
    // RX pair: DCH2 fills vospiBlock[0], DCH3 fills vospiBlock[1], cross-
    // chained so completing a block hardware-enables the partner in the same
    // cycle (CHCHNS=1 arms on channel n+1's completion, CHCHNS=0 on n-1's).
    // All capture channels run at top priority (0b11): the RX side has a
    // one-byte-time deadline against GLCD scanout on the DDR2 bus, and the
    // bench showed the TX side is the one that actually starves (every
    // observed stall was a TX stall) -- a late TX byte stops the clock
    // mid-packet, which makes the sensor abort the segment.
    DCH2CON = 0;
    DCH2CONbits.CHPRI = 0b11;
    DCH2CONbits.CHCHN = 1;
    DCH2CONbits.CHCHNS = 1;     // enabled when DCH3 completes its block
    DCH2ECON = 0;
    DCH2ECONbits.CHSIRQ = spi4_receive_done;
    DCH2ECONbits.SIRQEN = 1;
    DCH2SSA = KVA_TO_PA((uint32_t)&SPI4BUF);
    DCH2SSIZ = 1;
    DCH2DSA = KVA_TO_PA((uint32_t)vospiBlock[0]);
    DCH2DSIZ = FLIR_VOSPI_BLOCK_BYTES;
    DCH2CSIZ = 1;
    DCH2INT = 0;
    DCH2INTbits.CHBCIE = 1;

    DCH3CON = 0;
    DCH3CONbits.CHPRI = 0b11;
    DCH3CONbits.CHCHN = 1;
    DCH3CONbits.CHCHNS = 0;     // enabled when DCH2 completes its block
    DCH3ECON = 0;
    DCH3ECONbits.CHSIRQ = spi4_receive_done;
    DCH3ECONbits.SIRQEN = 1;
    DCH3SSA = KVA_TO_PA((uint32_t)&SPI4BUF);
    DCH3SSIZ = 1;
    DCH3DSA = KVA_TO_PA((uint32_t)vospiBlock[1]);
    DCH3DSIZ = FLIR_VOSPI_BLOCK_BYTES;
    DCH3CSIZ = 1;
    DCH3INT = 0;
    DCH3INTbits.CHBCIE = 1;

    // TX: a single channel (DCH4) with CHAEN -- "continuously enabled, not
    // automatically disabled after a block transfer completes". The channel
    // wraps its dummy-byte block forever, so crossing a block boundary is the
    // same operation as every intra-block byte (which runs 9,839 times per
    // block without fail), and there is no hand-off to miss. The cross-
    // chained TX pair this replaced stalled the clock at its hand-off ~3
    // times per second of streaming (bench 2026-07-29: 93 of 116 resyncs
    // were clock-stop deadlocks) while the RX pair never missed once.
    DCH4CON = 0;
    DCH4CONbits.CHPRI = 0b11;
    DCH4CONbits.CHAEN = 1;      // auto re-enable at block complete: clocks forever
    DCH4ECON = 0;
    DCH4ECONbits.CHSIRQ = spi4_transfer_done;
    DCH4ECONbits.SIRQEN = 1;
    DCH4SSA = KVA_TO_PA((uint32_t)vospiTxDummy);
    DCH4SSIZ = FLIR_VOSPI_BLOCK_BYTES;
    DCH4DSA = KVA_TO_PA((uint32_t)&SPI4BUF);
    DCH4DSIZ = 1;
    DCH4CSIZ = 1;
    DCH4INT = 0;

    // Block-complete interrupts on both RX channels (parse only -- the
    // re-arm is the hardware chain's job).
    setInterruptPriority(dma_channel_2, FLIR_VOSPI_DMA_IPL);
    setInterruptSubpriority(dma_channel_2, 0);
    clearInterruptFlag(dma_channel_2);
    setInterruptPriority(dma_channel_3, FLIR_VOSPI_DMA_IPL);
    setInterruptSubpriority(dma_channel_3, 0);
    clearInterruptFlag(dma_channel_3);
#else
    // RX channel (DCH2): SPI4BUF -> vospiBlock, one byte per SPI4-RX event.
    DCH2CON = 0;
    // Top DMA priority for both capture channels. RX has a one-byte-time
    // deadline against GLCD scanout on the DDR2 bus; and the bench showed TX
    // is the channel that actually starves (every observed stall was a TX
    // stall) -- a late TX byte stops the clock mid-packet and the sensor
    // aborts the segment. Ranking either below anything else costs frames.
    DCH2CONbits.CHPRI = 0b11;
    DCH2ECON = 0;
    DCH2ECONbits.CHSIRQ = spi4_receive_done;   // start cell on each RX event
    DCH2ECONbits.SIRQEN = 1;
    DCH2SSA = KVA_TO_PA((uint32_t)&SPI4BUF);
    DCH2SSIZ = 1;               // source is the 1-byte SPI FIFO (wraps)
    DCH2DSA = KVA_TO_PA((uint32_t)vospiBlock[0]);   // ArmBlock() re-points this
    DCH2DSIZ = FLIR_VOSPI_BLOCK_BYTES;         // block = one whole segment
    DCH2CSIZ = 1;               // one byte per event
    DCH2INT = 0;
    DCH2INTbits.CHBCIE = 1;     // interrupt on block (packet) complete

    // TX channel (DCH3): vospiTxDummy -> SPI4BUF, one byte per SPI4-TX event.
    DCH3CON = 0;
    DCH3CONbits.CHPRI = 0b11;   // same top priority -- see the RX note above
    DCH3ECON = 0;
    DCH3ECONbits.CHSIRQ = spi4_transfer_done;
    DCH3ECONbits.SIRQEN = 1;
    DCH3SSA = KVA_TO_PA((uint32_t)vospiTxDummy);
    DCH3SSIZ = FLIR_VOSPI_BLOCK_BYTES;         // clocks for one whole block
    DCH3DSA = KVA_TO_PA((uint32_t)&SPI4BUF);
    DCH3DSIZ = 1;               // dest is the 1-byte SPI FIFO (wraps)
    DCH3CSIZ = 1;
    DCH3INT = 0;

    // DMA block-complete interrupt (RX channel only).
    setInterruptPriority(dma_channel_2, FLIR_VOSPI_DMA_IPL);
    setInterruptSubpriority(dma_channel_2, 0);
    clearInterruptFlag(dma_channel_2);
#endif

    // --- VSYNC on INT1 (RD0 already PPS-mapped to INT1 in gpio setup) ---
    INTCONbits.INT1EP = 1;      // rising-edge triggered
    setInterruptPriority(external_interrupt_1, FLIR_VOSPI_VSYNC_IPL);
    setInterruptSubpriority(external_interrupt_1, 0);
    clearInterruptFlag(external_interrupt_1);

    // Frame buffers.
    captureFrame = (volatile uint16_t *)FLIR_VOSPI_FRAME_A_ADDRESS;
    readyFrame   = (volatile uint16_t *)FLIR_VOSPI_FRAME_B_ADDRESS;
    frameReadyFlag = false;

    memset((void *)FLIR_VOSPI_FRAME_A_ADDRESS, 0, FLIR_VOSPI_FRAME_SIZE_BYTES);
    memset((void *)FLIR_VOSPI_FRAME_B_ADDRESS, 0, FLIR_VOSPI_FRAME_SIZE_BYTES);

    memset(&stats, 0, sizeof(stats));
    FLIR_VOSPI_ResetSync();

    // Deassert CS; leave everything disarmed. The /CS idle clock starts now,
    // though FLIR_VOSPI_Start() takes a fresh window of its own anyway.
    captureRunning = false;
    capturePending = false;
    nFLIR_VOSPI_CS_PIN = HIGH;
    csIdleStartTicks = _CP0_GET_COUNT();
    lastProgressTicks = csIdleStartTicks;
}

#if FLIR_VOSPI_USE_CHAINED_DMA
// Arms the chained channels from a fully idle state (all channels disabled
// with their pointers at base, i.e. straight after FLIR_VOSPI_Disarm()). RX
// before TX so capture is listening before the first clock. After this, RX
// hand-offs are the hardware chain's and TX free-runs on CHAEN -- nothing
// here runs again until the next disarm.
static inline void FLIR_VOSPI_ArmChained(void)
{
    DCH2INTCLR = _DCH2INT_CHBCIF_MASK;
    DCH3INTCLR = _DCH3INT_CHBCIF_MASK;
    clearInterruptFlag(dma_channel_2);
    clearInterruptFlag(dma_channel_3);

    DCH2CONSET = _DCH2CON_CHEN_MASK;   // arm RX block A
    DCH4CONSET = _DCH4CON_CHEN_MASK;   // start TX (generates the clock, free-runs)
}
#else
// Re-arms both DMA channels for the next packet. RX first so it captures from
// the first clocked byte; then TX, which starts the clock. This is only valid
// straight after a block COMPLETED -- that is what returns DCHxSPTR/DCHxDPTR
// to SSA/DSA. Re-arming a block that was abandoned part-way needs CABORT
// first (FLIR_VOSPI_Disarm()).
static inline void FLIR_VOSPI_ArmBlock(void)
{
    DCH2DSA = KVA_TO_PA((uint32_t)vospiBlock[activeBlock]);

    DCH2INTCLR = _DCH2INT_CHBCIF_MASK;
    clearInterruptFlag(dma_channel_2);
    DCH2CONSET = _DCH2CON_CHEN_MASK;   // arm RX
    DCH3CONSET = _DCH3CON_CHEN_MASK;   // start TX (generates the clock)
}
#endif

// Stops clocking the sensor and starts the /CS idle window: DMA disarmed, /CS
// deasserted, frame assembly reset. Safe from the DMA ISR.
static void FLIR_VOSPI_Disarm(void)
{
    // CABORT, not just CHEN=0. DCHxSPTR/DCHxDPTR only return to SSA/DSA when a
    // block COMPLETES; a block abandoned part-way keeps its pointers, so
    // simply setting CHEN again would resume mid-buffer and every packet after
    // that would be assembled from a shifted offset. CABORT forces the
    // pointers back and clears CHEN.
#if FLIR_VOSPI_USE_CHAINED_DMA
    // TX first (stops feeding the clock), then the RX pair. An RX chain
    // event can still fire mid-sequence and set the partner's CHEN behind an
    // abort that already passed it, so CHEN is cleared on everything again
    // after every abort has landed.
    DCH4ECONSET = _DCH4ECON_CABORT_MASK;
    DCH2ECONSET = _DCH2ECON_CABORT_MASK;
    DCH3ECONSET = _DCH3ECON_CABORT_MASK;

    DCH2CONCLR = _DCH2CON_CHEN_MASK;
    DCH3CONCLR = _DCH3CON_CHEN_MASK;
    DCH4CONCLR = _DCH4CON_CHEN_MASK;

    // Clear the block-complete conditions so the resync path (which doesn't
    // re-arm) can't re-enter either RX ISR forever.
    DCH2INTCLR = _DCH2INT_CHBCIF_MASK;
    DCH3INTCLR = _DCH3INT_CHBCIF_MASK;
    clearInterruptFlag(dma_channel_2);
    clearInterruptFlag(dma_channel_3);
#else
    DCH2ECONSET = _DCH2ECON_CABORT_MASK;
    DCH3ECONSET = _DCH3ECON_CABORT_MASK;

    DCH2CONCLR = _DCH2CON_CHEN_MASK;
    DCH3CONCLR = _DCH3CON_CHEN_MASK;

    // Clear the block-complete condition the DMA ISR was entered on. Normally
    // FLIR_VOSPI_ArmBlock() does this; the resync path doesn't re-arm, so
    // without this the still-asserted flag would re-enter the ISR forever.
    DCH2INTCLR = _DCH2INT_CHBCIF_MASK;
    clearInterruptFlag(dma_channel_2);
#endif

    nFLIR_VOSPI_CS_PIN = HIGH;
    csIdleStartTicks = _CP0_GET_COUNT();

    captureRunning = false;
#if !FLIR_VOSPI_USE_CHAINED_DMA
    activeBlock = 0;   // restart the ping-pong from a known buffer
#endif

    consecutiveDesyncs = 0;
    blankBlockRun = 0;
    consecutiveUnsticks = 0;

    FLIR_VOSPI_ResetSync();
}

// Abandons the current byte alignment and schedules a fresh start once the
// sensor has had its ~185ms of idle /CS. Called from the DMA ISR on a packet-
// number break and from the stall watchdog in FLIR_VOSPI_Tasks().
static void FLIR_VOSPI_RequestResync(void)
{
    FLIR_VOSPI_Disarm();
    capturePending = true;
    stats.resyncCount++;
}

#if FLIR_VOSPI_USE_CHAINED_DMA
// Forces the enabled RX channel to take one byte out of the SPI RX FIFO --
// exactly the cell transfer the event machinery should have produced, so the
// byte lands where the DMA would have put it and the packet grid is
// untouched. Returns false if no RX channel is enabled or the force times out.
static bool FLIR_VOSPI_ForceRxCell(void)
{
    uint32_t start;

    if (DCH2CONbits.CHEN)
    {
        DCH2ECONSET = _DCH2ECON_CFORCE_MASK;
        start = _CP0_GET_COUNT();
        while (DCH2ECONbits.CFORCE)
        {
            if ((uint32_t)(_CP0_GET_COUNT() - start) > FLIR_VOSPI_CFORCE_TIMEOUT_TICKS) return false;
        }
        return true;
    }

    if (DCH3CONbits.CHEN)
    {
        DCH3ECONSET = _DCH3ECON_CFORCE_MASK;
        start = _CP0_GET_COUNT();
        while (DCH3ECONbits.CFORCE)
        {
            if ((uint32_t)(_CP0_GET_COUNT() - start) > FLIR_VOSPI_CFORCE_TIMEOUT_TICKS) return false;
        }
        return true;
    }

    return false;
}

// Recovers a stopped clock in place -- /CS stays low, no idle window.
//
// Why in-place recovery is alignment-safe: VoSPI packet framing is
// clock-count based on BOTH ends -- the sensor emits byte N of a packet slot
// as the Nth byte clocked since /CS assertion, and our RX chops the same
// continuous byte stream every 164 bytes. A paused clock delays the stream,
// it does not shift it; only losing RX bytes, or restarting the RX channels
// mid-stream, can misalign the grid. So neither draining the RX FIFO through
// the RX DMA nor aborting/restarting the TX channel touches alignment. (The
// stall itself may make the sensor abandon its current frame; that shows up
// as discard/desync packets and is soft-recovered by the parser.)
//
// The wedge comes in two flavors, told apart by the RX FIFO:
//
//  - RX FIFO holding bytes: the RX side stopped taking them. The bench
//    evidence (2026-07-29 round 4) is that this SPI, as an enhanced-buffer
//    MASTER, reacts to a full RX FIFO by pausing new transfers rather than
//    setting SPIROV -- the clock stops, rxOverflows stays 0 forever (which
//    is why that counter was previously misread as proof the RX chain was
//    sound), and restarting the TX side cannot help because its FIFO is
//    already full and the master is refusing to shift it. TX-restart
//    unsticks failing 3-for-3 on every real stall while diagnosing
//    "mid-block" is exactly this signature. Cure: walk the enabled RX
//    channel through the backlog with forced cell transfers; once there is
//    room, the master resumes shifting on its own.
//
//  - RX FIFO empty: the TX side genuinely stopped feeding the clock. Cure:
//    abort and re-enable the TX channel (the same software start
//    ArmChained uses, which has never failed on the bench). The
//    disabled/never-started/mid-block counters record what state it was
//    found in.
static void FLIR_VOSPI_UnstickClock(void)
{
    stats.clockUnsticks++;

    if (SPI4STATbits.SPIRBE == 0)
    {
        if (DCH2CONbits.CHEN || DCH3CONbits.CHEN)
        {
            uint32_t n;

            stats.unstickRxDrains++;

            // FIFO is 16 deep; a forced cell can also legitimately cross a
            // block boundary, firing the block-complete/chain machinery the
            // normal way.
            for (n = 0; (n < 16u) && (SPI4STATbits.SPIRBE == 0); n++)
            {
                if (!FLIR_VOSPI_ForceRxCell())
                {
                    break;
                }
            }
        }
        else
        {
            // Bytes waiting but NO enabled RX channel: the RX chain enable
            // itself was lost. There is no in-place recovery -- draining
            // without a live channel would throw bytes away and shift the
            // grid -- so pay for the /CS window immediately.
            stats.unstickRxDead++;
            FLIR_VOSPI_RequestResync();
        }
        return;
    }

    if ((DCH4CON & _DCH4CON_CHEN_MASK) == 0)
    {
        stats.unstickTxDisabled++;
    }
    else if (DCH4SPTR == 0)
    {
        stats.unstickTxNeverStarted++;
    }
    else
    {
        stats.unstickTxMidBlock++;
    }

    DCH4ECONSET = _DCH4ECON_CABORT_MASK;
    DCH4CONCLR = _DCH4CON_CHEN_MASK;
    DCH4CONSET = _DCH4CON_CHEN_MASK;
}
#endif

void FLIR_VOSPI_Start(void)
{
    if (captureRunning || capturePending)
    {
        return;   // idempotent
    }

    // Always take the full idle window rather than trying to prove /CS has
    // already been high long enough: CP0 Count wraps every ~43s, so an elapsed
    // time measured across an arbitrary idle cannot be trusted, and 200ms once
    // per "FLIR Stream On" is not worth the risk of starting mid-packet.
    FLIR_VOSPI_Disarm();

    setInterruptEnable(dma_channel_2, 1);
#if FLIR_VOSPI_USE_CHAINED_DMA
    setInterruptEnable(dma_channel_3, 1);
#endif
    setInterruptEnable(external_interrupt_1, 1);

    capturePending = true;
}

void FLIR_VOSPI_Stop(void)
{
    FLIR_VOSPI_Disarm();
    capturePending = false;

    setInterruptEnable(dma_channel_2, 0);
#if FLIR_VOSPI_USE_CHAINED_DMA
    setInterruptEnable(dma_channel_3, 0);
#endif
    setInterruptEnable(external_interrupt_1, 0);
}

void FLIR_VOSPI_Tasks(void)
{
    // All elapsed times below go through FLIR_VOSPI_TicksSince() -- the
    // stamps are written from ISR context, and reading CP0 before the stamp
    // wraps the subtraction when an ISR lands in between (see the helper).

    if (capturePending)
    {
        // Wait out the VoSPI re-synchronization window before touching /CS.
        if (FLIR_VOSPI_TicksSince(&csIdleStartTicks) <
                (FLIR_VOSPI_RESYNC_IDLE_MS * FLIR_VOSPI_TICKS_PER_MS))
        {
            return;
        }

        // Empty the SPI RX FIFO: a leftover byte here would offset every
        // packet that follows, which is the very failure being recovered from.
        SPI4STATbits.SPIROV = 0;
        while (SPI4STATbits.SPIRBE == 0)
        {
            (void)SPI4BUF;
        }

        FLIR_VOSPI_ResetSync();
        lastProgressTicks = _CP0_GET_COUNT();
        lastPacketTicks = lastProgressTicks;

        // Flags before arming: the DMA ISR can fire one packet time later.
        capturePending = false;
        captureRunning = true;

        nFLIR_VOSPI_CS_PIN = LOW;
#if FLIR_VOSPI_USE_CHAINED_DMA
        FLIR_VOSPI_ArmChained();
#else
        FLIR_VOSPI_ArmBlock();
#endif

        return;
    }

    // A receive overflow is not a statistic to note and carry on from: with
    // SPIROV set, SPI4 stops loading the RX FIFO altogether, so the RX DMA
    // stalls part-way through a block and no further RX events arrive -- the
    // capture goes silently dead mid-packet (a dump full of "FF 00 00 00 ..."
    // is this). Bytes were dropped, so alignment is gone too; the cure is the
    // same /CS idle window as a desync.
    if (captureRunning && SPI4STATbits.SPIROV)
    {
        stats.rxOverflows++;
        FLIR_VOSPI_RequestResync();
        return;
    }

#if FLIR_VOSPI_USE_CHAINED_DMA
    // Clock stopped (no completed block for 2+ block times, and no overflow,
    // so no bytes are being clocked at all): restart the TX side in place --
    // a ~20ms blip instead of the ~300ms detect-plus-/CS-window freeze this
    // used to cost. A few fruitless restarts in a row mean the problem is not
    // the TX channel; pay for the full resync.
    if (captureRunning &&
        (FLIR_VOSPI_TicksSince(&lastPacketTicks) >
                (FLIR_VOSPI_UNSTICK_MS * FLIR_VOSPI_TICKS_PER_MS)))
    {
        consecutiveUnsticks++;
        if (consecutiveUnsticks > FLIR_VOSPI_MAX_UNSTICKS)
        {
            stats.stallRecoveries++;
            FLIR_VOSPI_RequestResync();
            return;
        }

        FLIR_VOSPI_UnstickClock();

        // Restart the no-packet clock so the next check measures the restart,
        // not the original stall. (The RX ISR resets consecutiveUnsticks the
        // moment a block actually completes.)
        lastPacketTicks = _CP0_GET_COUNT();
        return;
    }
#endif

    // Deadlock: the byte stream itself has stopped (see FLIR_VOSPI_DEADLOCK_MS).
    // Recovering needs the full /CS idle window, not just a re-arm -- bytes
    // were lost, so the packet alignment is gone with them.
    if (captureRunning &&
        (FLIR_VOSPI_TicksSince(&lastPacketTicks) >
                (FLIR_VOSPI_DEADLOCK_MS * FLIR_VOSPI_TICKS_PER_MS)))
    {
        stats.stallRecoveries++;
        FLIR_VOSPI_RequestResync();
        return;
    }

    // Stall watchdog: no accepted packet for FLIR_VOSPI_STALL_TIMEOUT_MS means
    // either a hunt for a packet 0 that misalignment will never produce, or a
    // stream that has stopped (a lost DMA interrupt, the sensor re-booting).
    if (captureRunning &&
        (FLIR_VOSPI_TicksSince(&lastProgressTicks) >
                (FLIR_VOSPI_STALL_TIMEOUT_MS * FLIR_VOSPI_TICKS_PER_MS)))
    {
        FLIR_VOSPI_RequestResync();
    }
}

bool FLIR_VOSPI_FrameReady(void)
{
    return frameReadyFlag;
}

const uint16_t *FLIR_VOSPI_TakeFrame(void)
{
    if (!frameReadyFlag)
    {
        return NULL;
    }

    frameReadyFlag = false;
    return (const uint16_t *)readyFrame;
}

uint32_t FLIR_VOSPI_MsSinceLastPacket(void)
{
    if (!captureRunning)
    {
        return 0;
    }

    return FLIR_VOSPI_TicksSince(&lastPacketTicks) / FLIR_VOSPI_TICKS_PER_MS;
}

const char *FLIR_VOSPI_GetCaptureStateString(void)
{
    if (capturePending) return "resyncing (/CS idle window)";
    if (!captureRunning) return "idle";
    return haveSync ? "locked" : "hunting for segment start";
}

void FLIR_VOSPI_PrintPacketDump(void)
{
    uint8_t i, b;

    terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, BOLD_FONT);
    printf("    --- Last %u VoSPI packets (first %u of %u bytes, oldest first) ---\n\r",
           (unsigned)FLIR_VOSPI_DUMP_PACKETS, (unsigned)FLIR_VOSPI_DUMP_BYTES,
           (unsigned)FLIR_VOSPI_PACKET_BYTES);

    terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);

    if (stats.packetsCaptured == 0)
    {
        terminalTextAttributes(RED_COLOR, BLACK_COLOR, NORMAL_FONT);
        printf("    No packets have been captured at all -- the RX DMA has never\n\r");
        printf("    completed a block. Look at SPI4/DMA, not at the framing:\n\r");
        printf("    'Peripheral Status? FLIR SPI' (is DMA RX ch2 enabled? SPIROV?).\n\r");
        terminalTextAttributesReset();
        return;
    }

    // Oldest first: dumpNext points at the slot that will be written next,
    // which is the oldest entry once the ring has wrapped.
    for (i = 0; i < FLIR_VOSPI_DUMP_PACKETS; i++)
    {
        const uint8_t *p = dumpRing[(dumpNext + i) % FLIR_VOSPI_DUMP_PACKETS];

        printf("    ");
        for (b = 0; b < FLIR_VOSPI_DUMP_BYTES; b++) printf("%02X ", (unsigned)p[b]);

        // Decode the 4-byte header: ID (2 bytes) + CRC (2 bytes).
        if (FLIR_VOSPI_IS_DISCARD(p[0]))
        {
            printf("  discard\n\r");
        }
        else
        {
            printf("  packet %u", (unsigned)p[1]);
            if (p[1] == 20u) printf(", segment %u", (unsigned)((p[0] >> 4) & 0x07u));
            printf("\n\r");
        }
    }

    printf("    Packets: %lu total, %lu discards (%lu with data)\n\r",
           (unsigned long)stats.packetsCaptured, (unsigned long)stats.discardPackets,
           (unsigned long)(stats.packetsCaptured - stats.discardPackets));

    // Point at the likely cause rather than leaving the hex to be eyeballed.
    if (stats.discardPackets == stats.packetsCaptured)
    {
        terminalTextAttributes(YELLOW_COLOR, BLACK_COLOR, NORMAL_FONT);
        printf("    Every packet is a discard. If the bytes above are all FF the\n\r");
        printf("    sensor is not driving MISO (SDI4/RD7) at all -- check /CS (RD1),\n\r");
        printf("    the SPI4 PPS input mapping, and that SCK4 is really clocking.\n\r");
        printf("    If they are real 0x0Fxx headers the link is fine and the sensor\n\r");
        printf("    is simply producing no video (a CCI configuration problem).\n\r");
    }

    terminalTextAttributesReset();
}

void FLIR_VOSPI_GetStats(FLIR_VOSPI_STATS *out)
{
    if (out != NULL)
    {
        *out = stats;
    }
}

// Places one completed segment's 60 payloads into the capture frame buffer,
// byte-swapping and masking each pixel to 14 bits. seg is 1..4.
static void FLIR_VOSPI_PlaceSegment(uint8_t seg)
{
    uint32_t k;

    stats.segmentsPlaced++;
    if (seg <= FLIR_VOSPI_SEGMENTS_PER_FRAME) stats.segmentsPlacedById[seg]++;

    for (k = 0; k < FLIR_VOSPI_PACKETS_PER_SEGMENT; k++)
    {
        const uint8_t *src = &segScratch[k * FLIR_VOSPI_PACKET_PAYLOAD_BYTES];
        // Two packets per 160-pixel row; even packet = left 80px, odd = right.
        uint32_t row = ((uint32_t)(seg - 1) * 30u) + (k / 2u);
        uint32_t colStart = (k & 1u) * 80u;
        volatile uint16_t *dst = &captureFrame[(row * FLIR_VOSPI_WIDTH_PX) + colStart];
        uint32_t i;

        for (i = 0; i < 80u; i++)
        {
            // Full 16 bits, NOT masked to 14. The captured stream shows pixel
            // words like 0x73E4 / 0x70AF / 0x7C01 -- this Lepton 3.5 is
            // radiometric and outputs TLinear: value = temperature in
            // centi-Kelvin (0x73E4 = 29668 = 296.68K = 23.5C, room ambient;
            // 0x7C01 = 317.45K = 44.3C). Masking to 0x3FFF happens to look
            // right today only because every value in -109C..+54.5C has the
            // same top two bits; anything hotter than 54.5C wrapped to black.
            dst[i] = (uint16_t)(((uint16_t)src[i * 2u] << 8) | src[(i * 2u) + 1u]);
        }
    }
}

// Flips the freshly filled capture buffer to be the ready buffer, and points
// capture at the other one.
static void FLIR_VOSPI_CompleteFrame(void)
{
    volatile uint16_t *justFilled = captureFrame;

    readyFrame = justFilled;
    captureFrame = (justFilled == (volatile uint16_t *)FLIR_VOSPI_FRAME_A_ADDRESS)
                 ? (volatile uint16_t *)FLIR_VOSPI_FRAME_B_ADDRESS
                 : (volatile uint16_t *)FLIR_VOSPI_FRAME_A_ADDRESS;
    frameReadyFlag = true;
    stats.framesCaptured++;
}

// Walks one completed block packet by packet and accumulates segments/frames.
// Runs in the RX DMA block-complete ISR(s); integer-only per the ISR
// conventions (IPL5 shadow register set). It runs ~106 times a second and has
// the ~9.4ms of the next block to finish -- ample even for segment placement.
static void FLIR_VOSPI_ParseBlock(const uint8_t *block)
{
    uint32_t k;
    uint32_t blankInBlock = 0;

    for (k = 0; k < FLIR_VOSPI_PACKETS_PER_BLOCK; k++)
    {
        const uint8_t *pkt = &block[k * FLIR_VOSPI_PACKET_BYTES];
        uint8_t hdr0 = pkt[0];
        uint8_t pnum = pkt[1];

        // Snapshot for "FLIR Packet Dump" before any classification.
        memcpy(dumpRing[dumpNext], pkt, FLIR_VOSPI_DUMP_BYTES);
        dumpNext = (uint8_t)((dumpNext + 1u) % FLIR_VOSPI_DUMP_PACKETS);
        stats.packetsCaptured++;

        // A packet whose whole 4-byte header is zero is not a packet at all --
        // it is a dead MISO line being clocked into the buffer. A real packet
        // 0 carries a CRC in bytes 2..3 that is essentially never 0x0000.
        //
        // This must come before the packet-0 handling below, because
        // 00 00 00 00 otherwise reads as a perfectly good packet 0: the
        // restart rule resets the sequence, the packet is accepted, the next
        // zero packet restarts again... and the stream of nothing is consumed
        // forever while lastProgressTicks keeps being petted, so no watchdog
        // ever fires. That is exactly how the display once froze with 73,235
        // "segment restarts" against 100,024 packets -- a permanent freeze
        // with every counter looking healthy.
        if ((hdr0 == 0u) && (pnum == 0u) && (pkt[2] == 0u) && (pkt[3] == 0u))
        {
            stats.blankPackets++;
            blankInBlock++;
            continue;
        }

        // Discard/idle packets carry no image data.
        if (FLIR_VOSPI_IS_DISCARD(hdr0))
        {
            stats.discardPackets++;
            continue;
        }

        // Seek the start of a segment before trusting anything.
        if (!haveSync)
        {
            if (pnum != 0)
            {
                continue;
            }
            haveSync = true;
            expectedPacket = 0;
        }

        // Packet 0 unambiguously starts a new segment, whatever we were
        // expecting next. The sensor truncates the segments it marks invalid
        // rather than always emitting all 60 packets, so "expected 37, got 0"
        // is a normal segment restart, not a framing break -- counting it as a
        // desync (and dropping the lock over it) cost roughly one lost frame
        // per invalid segment. The partial segment simply never gets placed.
        if ((pnum == 0u) && (expectedPacket != 0u))
        {
            stats.segmentRestarts++;
            expectedPacket = 0;
            currentSegment = 0;
        }

        if (pnum != expectedPacket)
        {
            // Always a soft recovery: re-hunt for a packet 0 while continuing
            // to clock, never the 200ms /CS window.
            //
            // The previous rule paid a hard resync for any break at a block
            // boundary, on the theory that bytes lost across the re-arm had
            // shifted the packet grid. That premise was wrong: losing a byte
            // leaves the RX block one short, so it never completes and shows
            // up as a STALL, not as a completed block with bad packet numbers.
            // A desync therefore never implies lost byte alignment, and paying
            // 200ms for one cost ~5s of every 6.3s of run time -- capture was
            // idle in the resync window ~80% of the time. Genuine misalignment
            // is still caught, by the no-progress watchdog in
            // FLIR_VOSPI_Tasks() escalating to the /CS window.
            stats.desyncCount++;

            // Bound the churn. A misaligned grid still produces occasional
            // false locks onto bytes that happen to look like packet 0, and
            // each one pets the stall watchdog -- so misalignment could
            // otherwise persist for many watchdog periods, desyncing over and
            // over without escalating. Repeated breaks with no complete
            // segment in between mean the grid really is wrong: pay for the
            // /CS window now and get it right. (Bail out of the whole block
            // -- Disarm has just reset every piece of parse state.)
            consecutiveDesyncs++;
            if (consecutiveDesyncs >= FLIR_VOSPI_MAX_DESYNC_RUN)
            {
                FLIR_VOSPI_RequestResync();
                return;
            }

            FLIR_VOSPI_ResetSync();
            continue;
        }

        // Accepted packet: pet the stall watchdog and extend the run.
        // maxPacketRun is the honest measure of how close capture is getting
        // -- 60 is one whole segment, 240 unbroken is a frame.
        lastProgressTicks = lastPacketTicks;
        packetRun++;
        if (packetRun > stats.maxPacketRun) stats.maxPacketRun = packetRun;

        memcpy(&segScratch[pnum * FLIR_VOSPI_PACKET_PAYLOAD_BYTES],
               &pkt[FLIR_VOSPI_PACKET_HEADER_BYTES],
               FLIR_VOSPI_PACKET_PAYLOAD_BYTES);

        // The segment number is only meaningful in packet 20.
        if (pnum == 20u)
        {
            uint8_t seg = (uint8_t)((hdr0 >> 4) & 0x07u);

            stats.segmentIdSeen[seg]++;

            if ((seg < 1u) || (seg > FLIR_VOSPI_SEGMENTS_PER_FRAME))
            {
                // Segment id 0 is the sensor saying "this segment is not
                // valid, throw it away" -- normal and frequent, not an error.
                //
                // What must NOT happen here is the old ResetSync(): the packet
                // stream is perfectly in sync, only this segment's contents
                // are unusable. Dropping the lock over it meant re-hunting for
                // packet 0 every time, and with ~half of all segments coming
                // through invalid, four good ones could never accumulate back
                // to back -- which is exactly why frames stayed at 0 while
                // every other counter looked healthy.
                stats.segmentErrors++;
                currentSegment = 0;   // unusable; the stream stays locked
            }
            else
            {
                currentSegment = seg;
            }
        }

        if (pnum == (FLIR_VOSPI_PACKETS_PER_SEGMENT - 1u))
        {
            // A whole segment arrived in sequence, so the packet grid is
            // definitely right -- clear the misalignment evidence.
            consecutiveDesyncs = 0;

            // Segment complete. Only assemble frames from segments seen in
            // order starting at segment 1, so a mid-frame lock-on doesn't
            // stitch a torn frame together.
            if (currentSegment == 0u)
            {
                // Unusable segment (id 0 at packet 20, or we locked on after
                // packet 20 and never saw the id). Do nothing at all: no
                // placement, and crucially segmentMask is LEFT ALONE.
                //
                // We read a 60-packet block every ~9.4ms while the sensor
                // produces a real segment only every ~28.75ms, so it answers
                // with an id-0 segment roughly two times out of three -- they
                // fall BETWEEN the valid segments of a single frame. Clearing
                // the mask here (as the first version of this branch did)
                // therefore wiped the frame between segment 1 and segment 2
                // every time, which is why only segment 1s were ever placed
                // and no continuation ever ran.
            }
            else if (currentSegment == 1u)
            {
                segmentMask = 0x02u;   // bit for segment 1
                FLIR_VOSPI_PlaceSegment(1u);
            }
            else if (segmentMask & (1u << (currentSegment - 1u)))
            {
                // Previous segment in the run was placed -> this continues it.
                segmentMask |= (1u << currentSegment);
                FLIR_VOSPI_PlaceSegment(currentSegment);

                if ((currentSegment == FLIR_VOSPI_SEGMENTS_PER_FRAME) &&
                    (segmentMask == 0x1Eu))   // segments 1,2,3,4 all placed
                {
                    FLIR_VOSPI_CompleteFrame();
                    segmentMask = 0;
                }
            }
            else
            {
                // Out-of-order segment: wait for the next segment 1.
                segmentMask = 0;
            }

            expectedPacket = 0;
            currentSegment = 0;
        }
        else
        {
            expectedPacket++;
        }
    }

    // A block that was entirely blank means the sensor has stopped driving
    // MISO altogether. Nothing in the parser can recover that; only making
    // the sensor restart its stream will, so take the /CS window rather than
    // clocking in more of nothing -- but only after a few in a row (see
    // FLIR_VOSPI_BLANK_BLOCK_RUN for why reacting to the first one livelocks).
    if (blankInBlock == FLIR_VOSPI_PACKETS_PER_BLOCK)
    {
        stats.blankBlocks++;
        blankBlockRun++;

        if (blankBlockRun >= FLIR_VOSPI_BLANK_BLOCK_RUN)
        {
            FLIR_VOSPI_RequestResync();
        }
    }
    else
    {
        blankBlockRun = 0;
    }
}

#if FLIR_VOSPI_USE_CHAINED_DMA

// RX block A (DCH2) complete. The partner channel is already capturing -- the
// hardware chain enabled it in the same cycle this block finished -- so the
// only work here is the parse, with a whole block time of deadline.
void __ISR(_DMA2_VECTOR, IPL5SRS) flirVospiDmaISR(void)
{
    lastPacketTicks = _CP0_GET_COUNT();
    consecutiveUnsticks = 0;   // a completed block proves the clock is running

    DCH2INTCLR = _DCH2INT_CHBCIF_MASK;
    clearInterruptFlag(dma_channel_2);

    FLIR_VOSPI_ParseBlock(vospiBlock[0]);
}

// RX block B (DCH3) complete -- mirror of the above.
void __ISR(_DMA3_VECTOR, IPL5SRS) flirVospiDmaBISR(void)
{
    lastPacketTicks = _CP0_GET_COUNT();
    consecutiveUnsticks = 0;

    DCH3INTCLR = _DCH3INT_CHBCIF_MASK;
    clearInterruptFlag(dma_channel_3);

    FLIR_VOSPI_ParseBlock(vospiBlock[1]);
}

#else

// DMA channel 2 block-complete: a whole block of FLIR_VOSPI_PACKETS_PER_BLOCK
// packets has been captured into vospiBlock. Re-arm, then parse.
void __ISR(_DMA2_VECTOR, IPL5SRS) flirVospiDmaISR(void)
{
    const uint8_t *block = vospiBlock[activeBlock];

    lastPacketTicks = _CP0_GET_COUNT();

    // Re-arm into the OTHER buffer first, so the sensor's clock resumes
    // immediately and the parse below happens while the DMA is already
    // refilling. The DMA needs ~9.4ms to fill a block; the parse takes tens of
    // microseconds, so the two never collide.
    activeBlock ^= 1u;
    FLIR_VOSPI_ArmBlock();

    FLIR_VOSPI_ParseBlock(block);
}

#endif

// VSYNC rising edge from the Lepton (GPIO3 -> RD0 -> INT1). Frame-timing tick;
// the capture itself is DMA-driven, so this only keeps a count for now.
//
// NOTE: the Lepton does NOT drive VSYNC out of GPIO3 by default -- it has to
// be switched on with the OEM GPIO-mode CCI command, which lives in a
// protected module (the 0x4000 command bit) that flir_cci.c does not implement
// and whose code is not confirmed against FLIR doc #110-0144-04. So a
// vsyncCount of 0 is expected and is NOT evidence of an interrupt problem;
// nothing in the capture path depends on it.
void __ISR(_EXTERNAL_1_VECTOR, IPL4SRS) flirVsyncISR(void)
{
    stats.vsyncCount++;
    clearInterruptFlag(external_interrupt_1);
}

static uint32_t FLIR_VOSPI_GetBusSpeed(void)
{
    return FLIR_VOSPI_PBCLK_HZ / (2u * ((uint32_t)SPI4BRG + 1u));
}

void FLIR_VOSPI_PrintStatus(void)
{
    // MCU-peripheral view only (the SPI4/DMA/INT1 register settings behind the
    // VoSPI capture). Lepton module state and capture statistics live in
    // FLIR_PrintStatus() ("FLIR Status?").
    terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, BOLD_FONT);
    printf("    --- FLIR VoSPI MCU Peripherals (SPI4 / DMA / INT1) ---\n\r");

    // SPI4 controller.
    if (SPI4CONbits.ON) terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
    else terminalTextAttributes(RED_COLOR, BLACK_COLOR, NORMAL_FONT);
    printf("    SPI4 Module: %s\n\r", SPI4CONbits.ON ? "enabled" : "disabled");

    terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
    printf("    SPI4 Mode: master=%u, mode 3 (CKP=%u CKE=%u SMP=%u), %u-bit\n\r",
           (unsigned)SPI4CONbits.MSTEN, (unsigned)SPI4CONbits.CKP,
           (unsigned)SPI4CONbits.CKE, (unsigned)SPI4CONbits.SMP,
           SPI4CONbits.MODE32 ? 32u : (SPI4CONbits.MODE16 ? 16u : 8u));
    printf("    SPI4BRG: %u -> %lu Hz (PBCLK2 %lu Hz)\n\r",
           (unsigned)SPI4BRG, (unsigned long)FLIR_VOSPI_GetBusSpeed(),
           (unsigned long)FLIR_VOSPI_PBCLK_HZ);
    printf("    Enhanced buffer: %u  STXISEL=%u  SRXISEL=%u\n\r",
           (unsigned)SPI4CONbits.ENHBUF, (unsigned)SPI4CONbits.STXISEL,
           (unsigned)SPI4CONbits.SRXISEL);

    if (SPI4STATbits.SPIROV) terminalTextAttributes(RED_COLOR, BLACK_COLOR, NORMAL_FONT);
    else terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
    printf("    SPI4 receive overflow: %s\n\r", SPI4STATbits.SPIROV ? "occurred" : "none");

    // DMA channels.
    terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
#if FLIR_VOSPI_USE_CHAINED_DMA
    printf("    Chained-DMA capture (RX hardware ping-pong, TX free-running CHAEN)\n\r");
    printf("    DMA RX A/B (ch2/ch3): %s/%s  CHSIRQ=%u(SPI4RX)  block=%uB\n\r",
           DCH2CONbits.CHEN ? "enabled" : "disabled",
           DCH3CONbits.CHEN ? "enabled" : "disabled",
           (unsigned)DCH2ECONbits.CHSIRQ, (unsigned)DCH2DSIZ);
    printf("    DMA TX (ch4, CHAEN=%u): %s  CHSIRQ=%u(SPI4TX)  block=%uB\n\r",
           (unsigned)DCH4CONbits.CHAEN,
           DCH4CONbits.CHEN ? "enabled" : "disabled",
           (unsigned)DCH4ECONbits.CHSIRQ, (unsigned)DCH4SSIZ);
#else
    printf("    DMA RX (ch2): %s  CHSIRQ=%u(SPI4RX)  cell=%uB  block=%uB\n\r",
           DCH2CONbits.CHEN ? "enabled" : "disabled", (unsigned)DCH2ECONbits.CHSIRQ,
           (unsigned)DCH2CSIZ, (unsigned)DCH2DSIZ);
    printf("    DMA TX (ch3): %s  CHSIRQ=%u(SPI4TX)  cell=%uB  block=%uB\n\r",
           DCH3CONbits.CHEN ? "enabled" : "disabled", (unsigned)DCH3ECONbits.CHSIRQ,
           (unsigned)DCH3CSIZ, (unsigned)DCH3SSIZ);
#endif

    // Chip select GPIO and the VSYNC external interrupt.
    printf("    Chip Select (RD1, GPIO): %s\n\r", nFLIR_VOSPI_CS_PIN ? "deasserted" : "asserted");
    printf("    INT1 (VSYNC/RD0): %s, %s edge, priority %u\n\r",
           getInterruptEnable(external_interrupt_1) ? "enabled" : "disabled",
           INTCONbits.INT1EP ? "rising" : "falling",
           (unsigned)getInterruptPriority(external_interrupt_1));

    terminalTextAttributesReset();
}
