/*******************************************************************************
  FLIR Lepton VoSPI (Video over SPI) Capture Driver

  File Name:
    flir_vospi.c

  Summary:
    SPI4 + DMA capture and frame assembly for the Lepton 3.5. See flir_vospi.h
    for the VoSPI framing and the two-channel DMA capture design.
*******************************************************************************/

#include "application/flir/flir_vospi.h"
#include "core/device_control.h"
#include "core/32mzda_interrupt_control.h"
#include "gpio/pin_macros.h"
#include "usb_uart/terminal_control.h"

#include <xc.h>
#include <sys/kmem.h>
#include <sys/attribs.h>
#include <stdio.h>
#include <string.h>

// SPI4 is clocked from PBCLK2 (SYSCLK/3 = 66.67 MHz), same as SPI3 (spi3.c).
#define FLIR_VOSPI_PBCLK_HZ         (SYSCLK_INT / 3u)

// VoSPI clock. (Fsck = PBCLK/(2*(BRG+1)).) BRG=3 gives PBCLK2 / 8 = 8.33 MHz.
//
// This started at BRG=1 (16.67 MHz) on the "well under the Lepton's ~20 MHz
// limit" argument, which was the wrong thing to size against. The binding
// constraint is the RX DMA, not the sensor: at 16.67 MHz a byte lands every
// 32 PBCLK2 cycles, and that channel is competing for the bus with the GLCD
// scanning its framebuffer out of DDR2, LVGL drawing into it, and USB. Fall
// behind by a single byte and the block never completes (see
// FLIR_VOSPI_DEADLOCK_MS). 8.33 MHz doubles the service window per byte.
//
// There is throughput to spare: a segment is 60 packets = ~9.4ms of clocking
// here, so a whole 4-segment frame reads in ~38ms against a 115ms frame
// period -- 3x margin. Even 4.17 MHz (BRG=7) would work if this proves to
// still be too tight.
#define FLIR_VOSPI_BRG              3u

// DMA channels: DCH3 generates the clock (dummy TX), DCH2 captures RX. DMA
// channels 0/1 are the USB UART (usb_uart.h); 2/3 are otherwise free.
// Interrupt priorities: DMA at IPL5, VSYNC/INT1 at IPL4 -- both have their own
// shadow register set (PRISS, interruptControllerInitialize()) and sit clear
// of I2C (IPL7) and the USB UART (IPL1/2).
#define FLIR_VOSPI_DMA_IPL          5
#define FLIR_VOSPI_VSYNC_IPL        4

// A discard/idle packet has 0xF in the ID word's top nibble.
#define FLIR_VOSPI_IS_DISCARD(hdr0) (((hdr0) & 0x0Fu) == 0x0Fu)

// CP0 Count runs at SYSCLK/2 (same basis as flir.c).
#define FLIR_VOSPI_TICKS_PER_MS     ((uint32_t)(SYSCLK_INT / 2u) / 1000u)

// *** The VoSPI re-synchronization rule, and why the first version of this
// driver could never recover from a desync ***
//
// Everything the host reads is a byte stream: SCK is generated by us, and the
// Lepton simply shifts out whatever comes next. The 164-byte packet boundary
// is therefore decided entirely by where we START clocking -- if the first
// captured byte is not a packet's first header byte, EVERY subsequent 164-byte
// DMA block is the same rotated view of the stream, forever. Nothing in the
// data recovers it, because the sensor never inserts a gap to re-align to; the
// packet-number check just fails over and over (desyncCount climbing by
// thousands with frames=0 is exactly this).
//
// Per the Lepton engineering datasheet the only cure is to make the sensor
// itself restart its stream: de-assert /CS and keep the clock idle for at
// least 5 frame periods (~185ms), after which the next /CS assertion begins on
// a packet boundary. So a desync now disarms the DMA and schedules that idle
// window (FLIR_VOSPI_Tasks re-arms when it expires) instead of re-arming
// immediately.
#define FLIR_VOSPI_RESYNC_IDLE_MS   200u

// Deadlock detector. If the RX DMA ends up even one byte short of its block --
// a lost RX event, a byte dropped under bus contention -- the block never
// completes, and because our TX DMA has already finished its dummy bytes there
// are no more clocks coming to feed it. Capture then sits silently armed
// forever with no error flag anywhere: no SPIROV (nothing overflowed), no
// desync (no packet completed). That is the "frames=0, no errors, last packet
// N ms ago" signature. A block is ~9.4ms of clocking at 8.33MHz, so this is
// ~10 block times.
#define FLIR_VOSPI_DEADLOCK_MS      100u

// If no packet is accepted for this long, capture is either hunting a packet 0
// it will never find (misaligned) or the stream has stopped. Same cure either
// way. One frame period is ~115ms at 8.7fps, and after a resync the sensor
// legitimately sends discard packets until its next frame, so this is set well
// clear of that (~13 frames) -- an impatient watchdog here just livelocks the
// resync instead of letting the stream come back.
#define FLIR_VOSPI_STALL_TIMEOUT_MS 1500u

// --- Capture buffers -------------------------------------------------------

// Two blocks, ping-ponged: the ISR points the DMA at the far buffer and
// re-arms BEFORE it parses the one that just filled, so the clock restarts
// within a few hundred nanoseconds instead of pausing for the length of the
// parse. That gap matters -- with a single buffer, desyncs at a block boundary
// ran ~18x over-represented against breaks elsewhere in the stream (25 of 83,
// where an even spread predicts ~1.4), i.e. stopping the clock mid-segment was
// itself making the sensor abandon segments. Coherent (uncached) so the CPU
// sees exactly what DMA wrote, and word-aligned for the DMA engine.
static uint8_t vospiBlock[2][FLIR_VOSPI_BLOCK_BYTES] __attribute__((coherent, aligned(4)));

// Which of the two blocks the DMA is currently filling.
static volatile uint8_t activeBlock;

// Zero bytes clocked out to drive SCK for one block. Not const: the DMA engine
// reads it from RAM, and 'coherent' (uncached DMA memory) is incompatible with
// the .rodata section 'const' would place it in. Never written, so it stays
// all-zero (static zero-initialization). SDO4 goes nowhere the sensor listens,
// so the content is irrelevant -- only the clocks it generates matter.
static uint8_t vospiTxDummy[FLIR_VOSPI_BLOCK_BYTES] __attribute__((coherent, aligned(4)));

// One segment's raw payloads accumulate here (CPU-only, no DMA) until the
// segment completes and is placed into the frame buffer.
static uint8_t segScratch[FLIR_VOSPI_PACKETS_PER_SEGMENT * FLIR_VOSPI_PACKET_PAYLOAD_BYTES];

// Two DDR2 frame buffers (14-bit values). captureFrame is being filled;
// readyFrame is the last completed one handed to the app.
static volatile uint16_t *captureFrame;
static volatile uint16_t *readyFrame;
static volatile bool frameReadyFlag;

// --- Capture state machine (all touched only in the DMA ISR) ---------------
static bool     haveSync;         // locked onto the packet-0..59 sequence
static uint8_t  expectedPacket;   // next packet number we expect (0..59)
static uint8_t  currentSegment;   // segment id from packet 20 (1..4)
static uint8_t  segmentMask;      // bitmask of segments placed for this frame
static uint32_t packetRun;        // current unbroken in-sequence packet count
static FLIR_VOSPI_STATS stats;

// --- Packet dump ring (diagnostics) ----------------------------------------
// The leading bytes of the last few packets the DMA delivered, whatever they
// were. Written unconditionally at the top of the ISR so it also captures the
// cases the parser throws away (discards, misaligned windows).
static uint8_t dumpRing[FLIR_VOSPI_DUMP_PACKETS][FLIR_VOSPI_DUMP_BYTES];
static volatile uint8_t dumpNext;

// --- Capture arming / re-synchronization (ISR + thread context) ------------
static volatile bool     captureRunning;    // CS asserted, DMA armed
static volatile bool     capturePending;    // waiting out the /CS idle window
static volatile uint32_t csIdleStartTicks;  // CP0 Count when /CS went high
static volatile uint32_t lastProgressTicks; // CP0 Count of the last good packet
static volatile uint32_t lastPacketTicks;   // CP0 Count of the last packet of
                                            // ANY kind -- distinguishes "the
                                            // stream stopped" from "the stream
                                            // is running but never locks"

// Reset the frame-assembly state (called on start and on any desync).
static void FLIR_VOSPI_ResetSync(void)
{
    haveSync = false;
    expectedPacket = 0;
    currentSegment = 0;
    segmentMask = 0;
    packetRun = 0;
}

void FLIR_VOSPI_Initialize(void)
{
    // --- SPI4 (mirrors spi3.c, but VoSPI is SPI mode 3 and read-mostly) ---
    SPI4CONbits.ON = 0;
    SPI4STATbits.SPIROV = 0;
    (void)SPI4BUF;

    SPI4BRG = FLIR_VOSPI_BRG;

    SPI4CONbits.MSTEN = 1;      // master: we generate the clock for the slave
    SPI4CONbits.SIDL = 0;

    // SPI mode 3 for VoSPI: clock idles high, data sampled on the rising
    // (idle-to-active) edge. PIC32's CKE is inverted vs CPHA, so mode 3 is
    // CKP=1 / CKE=0.
    SPI4CONbits.CKP = 1;
    SPI4CONbits.CKE = 0;
    SPI4CONbits.SMP = 1;        // sample input at the end of the output time

    SPI4CONbits.MODE32 = 0;     // 8-bit words
    SPI4CONbits.MODE16 = 0;

    SPI4CONbits.SSEN = 0;       // CS is a plain GPIO (nFLIR_VOSPI_CS), not SS
    SPI4CONbits.MSSEN = 0;
    SPI4CONbits.MCLKSEL = 0;    // PBCLK, not REFCLK
    SPI4CONbits.FRMEN = 0;

    // Enhanced (FIFO) buffer mode with interrupts that pace the DMA: TX event
    // when the buffer can accept a byte, RX event when a byte has arrived.
    SPI4CONbits.ENHBUF = 1;
    SPI4CONbits.STXISEL = 0b01; // TX event: buffer not full
    SPI4CONbits.SRXISEL = 0b01; // RX event: buffer not empty

    SPI4CONbits.ON = 1;

    // --- DMA controller ---
    DMACONbits.ON = 1;          // idempotent; also enabled by the USB UART

    // RX channel (DCH2): SPI4BUF -> vospiBlock, one byte per SPI4-RX event.
    DCH2CON = 0;
    DCH2CONbits.CHPRI = 0b10;   // priority 2 (above the UART, below nothing critical)
    DCH2ECON = 0;
    DCH2ECONbits.CHSIRQ = spi4_receive_done;   // start cell on each RX event
    DCH2ECONbits.SIRQEN = 1;
    DCH2SSA = KVA_TO_PA((uint32_t)&SPI4BUF);
    DCH2SSIZ = 1;               // source is the 1-byte SPI FIFO (wraps)
    DCH2DSA = KVA_TO_PA((uint32_t)vospiBlock[0]);   // ArmBlock() re-points this
    DCH2DSIZ = FLIR_VOSPI_BLOCK_BYTES;         // block = one whole segment
    DCH2CSIZ = 1;               // one byte per event
    DCH2INT = 0;
    DCH2INTbits.CHBCIE = 1;     // interrupt on block (packet) complete

    // TX channel (DCH3): vospiTxDummy -> SPI4BUF, one byte per SPI4-TX event.
    DCH3CON = 0;
    DCH3CONbits.CHPRI = 0b10;
    DCH3ECON = 0;
    DCH3ECONbits.CHSIRQ = spi4_transfer_done;
    DCH3ECONbits.SIRQEN = 1;
    DCH3SSA = KVA_TO_PA((uint32_t)vospiTxDummy);
    DCH3SSIZ = FLIR_VOSPI_BLOCK_BYTES;         // clocks for one whole block
    DCH3DSA = KVA_TO_PA((uint32_t)&SPI4BUF);
    DCH3DSIZ = 1;               // dest is the 1-byte SPI FIFO (wraps)
    DCH3CSIZ = 1;
    DCH3INT = 0;

    // DMA block-complete interrupt (RX channel only).
    setInterruptPriority(dma_channel_2, FLIR_VOSPI_DMA_IPL);
    setInterruptSubpriority(dma_channel_2, 0);
    clearInterruptFlag(dma_channel_2);

    // --- VSYNC on INT1 (RD0 already PPS-mapped to INT1 in gpio setup) ---
    INTCONbits.INT1EP = 1;      // rising-edge triggered
    setInterruptPriority(external_interrupt_1, FLIR_VOSPI_VSYNC_IPL);
    setInterruptSubpriority(external_interrupt_1, 0);
    clearInterruptFlag(external_interrupt_1);

    // Frame buffers.
    captureFrame = (volatile uint16_t *)FLIR_VOSPI_FRAME_A_ADDRESS;
    readyFrame   = (volatile uint16_t *)FLIR_VOSPI_FRAME_B_ADDRESS;
    frameReadyFlag = false;

    memset((void *)FLIR_VOSPI_FRAME_A_ADDRESS, 0, FLIR_VOSPI_FRAME_SIZE_BYTES);
    memset((void *)FLIR_VOSPI_FRAME_B_ADDRESS, 0, FLIR_VOSPI_FRAME_SIZE_BYTES);

    memset(&stats, 0, sizeof(stats));
    FLIR_VOSPI_ResetSync();

    // Deassert CS; leave everything disarmed. The /CS idle clock starts now,
    // though FLIR_VOSPI_Start() takes a fresh window of its own anyway.
    captureRunning = false;
    capturePending = false;
    nFLIR_VOSPI_CS_PIN = HIGH;
    csIdleStartTicks = _CP0_GET_COUNT();
    lastProgressTicks = csIdleStartTicks;
}

// Re-arms both DMA channels for the next packet. RX first so it captures from
// the first clocked byte; then TX, which starts the clock. This is only valid
// straight after a block COMPLETED -- that is what returns DCHxSPTR/DCHxDPTR
// to SSA/DSA. Re-arming a block that was abandoned part-way needs CABORT
// first (FLIR_VOSPI_Disarm()).
static inline void FLIR_VOSPI_ArmBlock(void)
{
    DCH2DSA = KVA_TO_PA((uint32_t)vospiBlock[activeBlock]);

    DCH2INTCLR = _DCH2INT_CHBCIF_MASK;
    clearInterruptFlag(dma_channel_2);
    DCH2CONSET = _DCH2CON_CHEN_MASK;   // arm RX
    DCH3CONSET = _DCH3CON_CHEN_MASK;   // start TX (generates the clock)
}

// Stops clocking the sensor and starts the /CS idle window: DMA disarmed, /CS
// deasserted, frame assembly reset. Safe from the DMA ISR.
static void FLIR_VOSPI_Disarm(void)
{
    // CABORT, not just CHEN=0. DCHxSPTR/DCHxDPTR only return to SSA/DSA when a
    // block COMPLETES; a block abandoned part-way keeps its pointers, so
    // simply setting CHEN again would resume mid-buffer and every packet after
    // that would be assembled from a shifted offset. CABORT forces the
    // pointers back and clears CHEN.
    DCH2ECONSET = _DCH2ECON_CABORT_MASK;
    DCH3ECONSET = _DCH3ECON_CABORT_MASK;

    DCH2CONCLR = _DCH2CON_CHEN_MASK;
    DCH3CONCLR = _DCH3CON_CHEN_MASK;

    // Clear the block-complete condition the DMA ISR was entered on. Normally
    // FLIR_VOSPI_ArmBlock() does this; the resync path doesn't re-arm, so
    // without this the still-asserted flag would re-enter the ISR forever.
    DCH2INTCLR = _DCH2INT_CHBCIF_MASK;
    clearInterruptFlag(dma_channel_2);

    nFLIR_VOSPI_CS_PIN = HIGH;
    csIdleStartTicks = _CP0_GET_COUNT();

    captureRunning = false;
    activeBlock = 0;   // restart the ping-pong from a known buffer

    FLIR_VOSPI_ResetSync();
}

// Abandons the current byte alignment and schedules a fresh start once the
// sensor has had its ~185ms of idle /CS. Called from the DMA ISR on a packet-
// number break and from the stall watchdog in FLIR_VOSPI_Tasks().
static void FLIR_VOSPI_RequestResync(void)
{
    FLIR_VOSPI_Disarm();
    capturePending = true;
    stats.resyncCount++;
}

void FLIR_VOSPI_Start(void)
{
    if (captureRunning || capturePending)
    {
        return;   // idempotent
    }

    // Always take the full idle window rather than trying to prove /CS has
    // already been high long enough: CP0 Count wraps every ~43s, so an elapsed
    // time measured across an arbitrary idle cannot be trusted, and 200ms once
    // per "FLIR Stream On" is not worth the risk of starting mid-packet.
    FLIR_VOSPI_Disarm();

    setInterruptEnable(dma_channel_2, 1);
    setInterruptEnable(external_interrupt_1, 1);

    capturePending = true;
}

void FLIR_VOSPI_Stop(void)
{
    FLIR_VOSPI_Disarm();
    capturePending = false;

    setInterruptEnable(dma_channel_2, 0);
    setInterruptEnable(external_interrupt_1, 0);
}

void FLIR_VOSPI_Tasks(void)
{
    uint32_t now = _CP0_GET_COUNT();

    if (capturePending)
    {
        // Wait out the VoSPI re-synchronization window before touching /CS.
        if ((uint32_t)(now - csIdleStartTicks) <
                (FLIR_VOSPI_RESYNC_IDLE_MS * FLIR_VOSPI_TICKS_PER_MS))
        {
            return;
        }

        // Empty the SPI RX FIFO: a leftover byte here would offset every
        // packet that follows, which is the very failure being recovered from.
        SPI4STATbits.SPIROV = 0;
        while (SPI4STATbits.SPIRBE == 0)
        {
            (void)SPI4BUF;
        }

        FLIR_VOSPI_ResetSync();
        lastProgressTicks = _CP0_GET_COUNT();
        lastPacketTicks = lastProgressTicks;

        // Flags before arming: the DMA ISR can fire one packet time later.
        capturePending = false;
        captureRunning = true;

        nFLIR_VOSPI_CS_PIN = LOW;
        FLIR_VOSPI_ArmBlock();

        return;
    }

    // A receive overflow is not a statistic to note and carry on from: with
    // SPIROV set, SPI4 stops loading the RX FIFO altogether, so the RX DMA
    // stalls part-way through a block and no further RX events arrive -- the
    // capture goes silently dead mid-packet (a dump full of "FF 00 00 00 ..."
    // is this). Bytes were dropped, so alignment is gone too; the cure is the
    // same /CS idle window as a desync.
    if (captureRunning && SPI4STATbits.SPIROV)
    {
        stats.rxOverflows++;
        FLIR_VOSPI_RequestResync();
        return;
    }

    // Deadlock: the byte stream itself has stopped (see FLIR_VOSPI_DEADLOCK_MS).
    // Recovering needs the full /CS idle window, not just a re-arm -- bytes
    // were lost, so the packet alignment is gone with them.
    if (captureRunning &&
        ((uint32_t)(now - lastPacketTicks) >
                (FLIR_VOSPI_DEADLOCK_MS * FLIR_VOSPI_TICKS_PER_MS)))
    {
        stats.stallRecoveries++;
        FLIR_VOSPI_RequestResync();
        return;
    }

    // Stall watchdog: no accepted packet for FLIR_VOSPI_STALL_TIMEOUT_MS means
    // either a hunt for a packet 0 that misalignment will never produce, or a
    // stream that has stopped (a lost DMA interrupt, the sensor re-booting).
    if (captureRunning &&
        ((uint32_t)(now - lastProgressTicks) >
                (FLIR_VOSPI_STALL_TIMEOUT_MS * FLIR_VOSPI_TICKS_PER_MS)))
    {
        FLIR_VOSPI_RequestResync();
    }
}

bool FLIR_VOSPI_FrameReady(void)
{
    return frameReadyFlag;
}

const uint16_t *FLIR_VOSPI_TakeFrame(void)
{
    if (!frameReadyFlag)
    {
        return NULL;
    }

    frameReadyFlag = false;
    return (const uint16_t *)readyFrame;
}

uint32_t FLIR_VOSPI_MsSinceLastPacket(void)
{
    if (!captureRunning)
    {
        return 0;
    }

    return (uint32_t)(_CP0_GET_COUNT() - lastPacketTicks) / FLIR_VOSPI_TICKS_PER_MS;
}

const char *FLIR_VOSPI_GetCaptureStateString(void)
{
    if (capturePending) return "resyncing (/CS idle window)";
    if (!captureRunning) return "idle";
    return haveSync ? "locked" : "hunting for segment start";
}

void FLIR_VOSPI_PrintPacketDump(void)
{
    uint8_t i, b;

    terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, BOLD_FONT);
    printf("    --- Last %u VoSPI packets (first %u of %u bytes, oldest first) ---\n\r",
           (unsigned)FLIR_VOSPI_DUMP_PACKETS, (unsigned)FLIR_VOSPI_DUMP_BYTES,
           (unsigned)FLIR_VOSPI_PACKET_BYTES);

    terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);

    if (stats.packetsCaptured == 0)
    {
        terminalTextAttributes(RED_COLOR, BLACK_COLOR, NORMAL_FONT);
        printf("    No packets have been captured at all -- the RX DMA has never\n\r");
        printf("    completed a block. Look at SPI4/DMA, not at the framing:\n\r");
        printf("    'Peripheral Status? FLIR SPI' (is DMA RX ch2 enabled? SPIROV?).\n\r");
        terminalTextAttributesReset();
        return;
    }

    // Oldest first: dumpNext points at the slot that will be written next,
    // which is the oldest entry once the ring has wrapped.
    for (i = 0; i < FLIR_VOSPI_DUMP_PACKETS; i++)
    {
        const uint8_t *p = dumpRing[(dumpNext + i) % FLIR_VOSPI_DUMP_PACKETS];

        printf("    ");
        for (b = 0; b < FLIR_VOSPI_DUMP_BYTES; b++) printf("%02X ", (unsigned)p[b]);

        // Decode the 4-byte header: ID (2 bytes) + CRC (2 bytes).
        if (FLIR_VOSPI_IS_DISCARD(p[0]))
        {
            printf("  discard\n\r");
        }
        else
        {
            printf("  packet %u", (unsigned)p[1]);
            if (p[1] == 20u) printf(", segment %u", (unsigned)((p[0] >> 4) & 0x07u));
            printf("\n\r");
        }
    }

    printf("    Packets: %lu total, %lu discards (%lu with data)\n\r",
           (unsigned long)stats.packetsCaptured, (unsigned long)stats.discardPackets,
           (unsigned long)(stats.packetsCaptured - stats.discardPackets));

    // Point at the likely cause rather than leaving the hex to be eyeballed.
    if (stats.discardPackets == stats.packetsCaptured)
    {
        terminalTextAttributes(YELLOW_COLOR, BLACK_COLOR, NORMAL_FONT);
        printf("    Every packet is a discard. If the bytes above are all FF the\n\r");
        printf("    sensor is not driving MISO (SDI4/RD7) at all -- check /CS (RD1),\n\r");
        printf("    the SPI4 PPS input mapping, and that SCK4 is really clocking.\n\r");
        printf("    If they are real 0x0Fxx headers the link is fine and the sensor\n\r");
        printf("    is simply producing no video (a CCI configuration problem).\n\r");
    }

    terminalTextAttributesReset();
}

void FLIR_VOSPI_GetStats(FLIR_VOSPI_STATS *out)
{
    if (out != NULL)
    {
        *out = stats;
    }
}

// Places one completed segment's 60 payloads into the capture frame buffer,
// byte-swapping and masking each pixel to 14 bits. seg is 1..4.
static void FLIR_VOSPI_PlaceSegment(uint8_t seg)
{
    uint32_t k;

    stats.segmentsPlaced++;
    if (seg <= FLIR_VOSPI_SEGMENTS_PER_FRAME) stats.segmentsPlacedById[seg]++;

    for (k = 0; k < FLIR_VOSPI_PACKETS_PER_SEGMENT; k++)
    {
        const uint8_t *src = &segScratch[k * FLIR_VOSPI_PACKET_PAYLOAD_BYTES];
        // Two packets per 160-pixel row; even packet = left 80px, odd = right.
        uint32_t row = ((uint32_t)(seg - 1) * 30u) + (k / 2u);
        uint32_t colStart = (k & 1u) * 80u;
        volatile uint16_t *dst = &captureFrame[(row * FLIR_VOSPI_WIDTH_PX) + colStart];
        uint32_t i;

        for (i = 0; i < 80u; i++)
        {
            // Full 16 bits, NOT masked to 14. The captured stream shows pixel
            // words like 0x73E4 / 0x70AF / 0x7C01 -- this Lepton 3.5 is
            // radiometric and outputs TLinear: value = temperature in
            // centi-Kelvin (0x73E4 = 29668 = 296.68K = 23.5C, room ambient;
            // 0x7C01 = 317.45K = 44.3C). Masking to 0x3FFF happens to look
            // right today only because every value in -109C..+54.5C has the
            // same top two bits; anything hotter than 54.5C wrapped to black.
            dst[i] = (uint16_t)(((uint16_t)src[i * 2u] << 8) | src[(i * 2u) + 1u]);
        }
    }
}

// Flips the freshly filled capture buffer to be the ready buffer, and points
// capture at the other one.
static void FLIR_VOSPI_CompleteFrame(void)
{
    volatile uint16_t *justFilled = captureFrame;

    readyFrame = justFilled;
    captureFrame = (justFilled == (volatile uint16_t *)FLIR_VOSPI_FRAME_A_ADDRESS)
                 ? (volatile uint16_t *)FLIR_VOSPI_FRAME_B_ADDRESS
                 : (volatile uint16_t *)FLIR_VOSPI_FRAME_A_ADDRESS;
    frameReadyFlag = true;
    stats.framesCaptured++;
}

// DMA channel 2 block-complete: a whole block of FLIR_VOSPI_PACKETS_PER_BLOCK
// packets has been captured into vospiBlock. Walk it packet by packet,
// accumulate, then re-arm. Integer-only per the ISR conventions (IPL5 shadow
// register set); it runs ~106 times a second rather than ~6,400, and has the
// ~9.4ms of the next block to finish -- ample even for the segment placement.
void __ISR(_DMA2_VECTOR, IPL5SRS) flirVospiDmaISR(void)
{
    const uint8_t *block = vospiBlock[activeBlock];
    uint32_t k;

    lastPacketTicks = _CP0_GET_COUNT();

    // Re-arm into the OTHER buffer first, so the sensor's clock resumes
    // immediately and the parse below happens while the DMA is already
    // refilling. The DMA needs ~9.4ms to fill a block; the parse takes tens of
    // microseconds, so the two never collide.
    activeBlock ^= 1u;
    FLIR_VOSPI_ArmBlock();

    for (k = 0; k < FLIR_VOSPI_PACKETS_PER_BLOCK; k++)
    {
        const uint8_t *pkt = &block[k * FLIR_VOSPI_PACKET_BYTES];
        uint8_t hdr0 = pkt[0];
        uint8_t pnum = pkt[1];

        // Snapshot for "FLIR Packet Dump" before any classification.
        memcpy(dumpRing[dumpNext], pkt, FLIR_VOSPI_DUMP_BYTES);
        dumpNext = (uint8_t)((dumpNext + 1u) % FLIR_VOSPI_DUMP_PACKETS);
        stats.packetsCaptured++;

        // Discard/idle packets carry no image data.
        if (FLIR_VOSPI_IS_DISCARD(hdr0))
        {
            stats.discardPackets++;
            continue;
        }

        // Seek the start of a segment before trusting anything.
        if (!haveSync)
        {
            if (pnum != 0)
            {
                continue;
            }
            haveSync = true;
            expectedPacket = 0;
        }

        // Packet 0 unambiguously starts a new segment, whatever we were
        // expecting next. The sensor truncates the segments it marks invalid
        // rather than always emitting all 60 packets, so "expected 37, got 0"
        // is a normal segment restart, not a framing break -- counting it as a
        // desync (and dropping the lock over it) cost roughly one lost frame
        // per invalid segment. The partial segment simply never gets placed.
        if ((pnum == 0u) && (expectedPacket != 0u))
        {
            stats.segmentRestarts++;
            expectedPacket = 0;
            currentSegment = 0;
        }

        if (pnum != expectedPacket)
        {
            // Always a soft recovery: re-hunt for a packet 0 while continuing
            // to clock, never the 200ms /CS window.
            //
            // The previous rule paid a hard resync for any break at a block
            // boundary, on the theory that bytes lost across the re-arm had
            // shifted the packet grid. That premise was wrong: losing a byte
            // leaves the RX block one short, so it never completes and shows
            // up as a STALL, not as a completed block with bad packet numbers.
            // A desync therefore never implies lost byte alignment, and paying
            // 200ms for one cost ~5s of every 6.3s of run time -- capture was
            // idle in the resync window ~80% of the time. Genuine misalignment
            // is still caught, by the no-progress watchdog in
            // FLIR_VOSPI_Tasks() escalating to the /CS window.
            stats.desyncCount++;
            FLIR_VOSPI_ResetSync();
            continue;
        }

        // Accepted packet: pet the stall watchdog and extend the run.
        // maxPacketRun is the honest measure of how close capture is getting
        // -- 60 is one whole segment, 240 unbroken is a frame.
        lastProgressTicks = lastPacketTicks;
        packetRun++;
        if (packetRun > stats.maxPacketRun) stats.maxPacketRun = packetRun;

        memcpy(&segScratch[pnum * FLIR_VOSPI_PACKET_PAYLOAD_BYTES],
               &pkt[FLIR_VOSPI_PACKET_HEADER_BYTES],
               FLIR_VOSPI_PACKET_PAYLOAD_BYTES);

        // The segment number is only meaningful in packet 20.
        if (pnum == 20u)
        {
            uint8_t seg = (uint8_t)((hdr0 >> 4) & 0x07u);

            stats.segmentIdSeen[seg]++;

            if ((seg < 1u) || (seg > FLIR_VOSPI_SEGMENTS_PER_FRAME))
            {
                // Segment id 0 is the sensor saying "this segment is not
                // valid, throw it away" -- normal and frequent, not an error.
                //
                // What must NOT happen here is the old ResetSync(): the packet
                // stream is perfectly in sync, only this segment's contents
                // are unusable. Dropping the lock over it meant re-hunting for
                // packet 0 every time, and with ~half of all segments coming
                // through invalid, four good ones could never accumulate back
                // to back -- which is exactly why frames stayed at 0 while
                // every other counter looked healthy.
                stats.segmentErrors++;
                currentSegment = 0;   // unusable; the stream stays locked
            }
            else
            {
                currentSegment = seg;
            }
        }

        if (pnum == (FLIR_VOSPI_PACKETS_PER_SEGMENT - 1u))
        {
            // Segment complete. Only assemble frames from segments seen in
            // order starting at segment 1, so a mid-frame lock-on doesn't
            // stitch a torn frame together.
            if (currentSegment == 0u)
            {
                // Unusable segment (id 0 at packet 20, or we locked on after
                // packet 20 and never saw the id). Do nothing at all: no
                // placement, and crucially segmentMask is LEFT ALONE.
                //
                // We read a 60-packet block every ~9.4ms while the sensor
                // produces a real segment only every ~28.75ms, so it answers
                // with an id-0 segment roughly two times out of three -- they
                // fall BETWEEN the valid segments of a single frame. Clearing
                // the mask here (as the first version of this branch did)
                // therefore wiped the frame between segment 1 and segment 2
                // every time, which is why only segment 1s were ever placed
                // and no continuation ever ran.
            }
            else if (currentSegment == 1u)
            {
                segmentMask = 0x02u;   // bit for segment 1
                FLIR_VOSPI_PlaceSegment(1u);
            }
            else if (segmentMask & (1u << (currentSegment - 1u)))
            {
                // Previous segment in the run was placed -> this continues it.
                segmentMask |= (1u << currentSegment);
                FLIR_VOSPI_PlaceSegment(currentSegment);

                if ((currentSegment == FLIR_VOSPI_SEGMENTS_PER_FRAME) &&
                    (segmentMask == 0x1Eu))   // segments 1,2,3,4 all placed
                {
                    FLIR_VOSPI_CompleteFrame();
                    segmentMask = 0;
                }
            }
            else
            {
                // Out-of-order segment: wait for the next segment 1.
                segmentMask = 0;
            }

            expectedPacket = 0;
            currentSegment = 0;
        }
        else
        {
            expectedPacket++;
        }
    }

    // No re-arm here -- it already happened at the top of this ISR.
}

// VSYNC rising edge from the Lepton (GPIO3 -> RD0 -> INT1). Frame-timing tick;
// the capture itself is DMA-driven, so this only keeps a count for now.
//
// NOTE: the Lepton does NOT drive VSYNC out of GPIO3 by default -- it has to
// be switched on with the OEM GPIO-mode CCI command, which lives in a
// protected module (the 0x4000 command bit) that flir_cci.c does not implement
// and whose code is not confirmed against FLIR doc #110-0144-04. So a
// vsyncCount of 0 is expected and is NOT evidence of an interrupt problem;
// nothing in the capture path depends on it.
void __ISR(_EXTERNAL_1_VECTOR, IPL4SRS) flirVsyncISR(void)
{
    stats.vsyncCount++;
    clearInterruptFlag(external_interrupt_1);
}

static uint32_t FLIR_VOSPI_GetBusSpeed(void)
{
    return FLIR_VOSPI_PBCLK_HZ / (2u * ((uint32_t)SPI4BRG + 1u));
}

void FLIR_VOSPI_PrintStatus(void)
{
    // MCU-peripheral view only (the SPI4/DMA/INT1 register settings behind the
    // VoSPI capture). Lepton module state and capture statistics live in
    // FLIR_PrintStatus() ("FLIR Status?").
    terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, BOLD_FONT);
    printf("    --- FLIR VoSPI MCU Peripherals (SPI4 / DMA / INT1) ---\n\r");

    // SPI4 controller.
    if (SPI4CONbits.ON) terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
    else terminalTextAttributes(RED_COLOR, BLACK_COLOR, NORMAL_FONT);
    printf("    SPI4 Module: %s\n\r", SPI4CONbits.ON ? "enabled" : "disabled");

    terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
    printf("    SPI4 Mode: master=%u, mode 3 (CKP=%u CKE=%u SMP=%u), %u-bit\n\r",
           (unsigned)SPI4CONbits.MSTEN, (unsigned)SPI4CONbits.CKP,
           (unsigned)SPI4CONbits.CKE, (unsigned)SPI4CONbits.SMP,
           SPI4CONbits.MODE32 ? 32u : (SPI4CONbits.MODE16 ? 16u : 8u));
    printf("    SPI4BRG: %u -> %lu Hz (PBCLK2 %lu Hz)\n\r",
           (unsigned)SPI4BRG, (unsigned long)FLIR_VOSPI_GetBusSpeed(),
           (unsigned long)FLIR_VOSPI_PBCLK_HZ);
    printf("    Enhanced buffer: %u  STXISEL=%u  SRXISEL=%u\n\r",
           (unsigned)SPI4CONbits.ENHBUF, (unsigned)SPI4CONbits.STXISEL,
           (unsigned)SPI4CONbits.SRXISEL);

    if (SPI4STATbits.SPIROV) terminalTextAttributes(RED_COLOR, BLACK_COLOR, NORMAL_FONT);
    else terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
    printf("    SPI4 receive overflow: %s\n\r", SPI4STATbits.SPIROV ? "occurred" : "none");

    // DMA channels.
    terminalTextAttributes(GREEN_COLOR, BLACK_COLOR, NORMAL_FONT);
    printf("    DMA RX (ch2): %s  CHSIRQ=%u(SPI4RX)  cell=%uB  block=%uB\n\r",
           DCH2CONbits.CHEN ? "enabled" : "disabled", (unsigned)DCH2ECONbits.CHSIRQ,
           (unsigned)DCH2CSIZ, (unsigned)DCH2DSIZ);
    printf("    DMA TX (ch3): %s  CHSIRQ=%u(SPI4TX)  cell=%uB  block=%uB\n\r",
           DCH3CONbits.CHEN ? "enabled" : "disabled", (unsigned)DCH3ECONbits.CHSIRQ,
           (unsigned)DCH3CSIZ, (unsigned)DCH3SSIZ);

    // Chip select GPIO and the VSYNC external interrupt.
    printf("    Chip Select (RD1, GPIO): %s\n\r", nFLIR_VOSPI_CS_PIN ? "deasserted" : "asserted");
    printf("    INT1 (VSYNC/RD0): %s, %s edge, priority %u\n\r",
           getInterruptEnable(external_interrupt_1) ? "enabled" : "disabled",
           INTCONbits.INT1EP ? "rising" : "falling",
           (unsigned)getInterruptPriority(external_interrupt_1));

    terminalTextAttributesReset();
}
