set(FILE_GROUP_assemble "")
set(FILE_GROUP_assembleWithPreprocess "")
set(FILE_GROUP_compile "../../../../main.c")
set(FILE_GROUP_compile_cpp "")
set(FILE_GROUP_link "")
set(BUILD_LIBRARY 0)
set(internal_image_name "c:/Users/drewm/OneDrive/Documents/KiCad Projects/Projects/Thermal_Camera/rev_a/sfw/U1701_firmware/Thermal_Camera.X/_build_mplab/Thermal_Camera/default/image_default.elf/default.elf")
set(image_name "default.elf")
set(output_dir "c:/Users/drewm/OneDrive/Documents/KiCad Projects/Projects/Thermal_Camera/rev_a/sfw/U1701_firmware/Thermal_Camera.X/out/Thermal_Camera")
