function(assemble_rule target)
    set(inputVar "${ASSEMBLER_PRE};-g;-mprocessor=32MZ2064DAR176;-Wa,--defsym=__MPLAB_BUILD=1,${MP_EXTRA_AS_POST};-mdfp=C:/Users/drewm/.mchp_packs/Microchip/PIC32MZ-DA_DFP/1.5.231")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
function(assembleWithPreprocess_rule target)
    set(inputVar "${MP_EXTRA_AS_PRE};-g;-mprocessor=32MZ2064DAR176;-DXPRJ_default=default;-Wa,--defsym=__MPLAB_BUILD=1,${MP_EXTRA_AS_POST}")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
function(compile_rule target)
    set(inputVar "${CC_PRE};-g;-x;c;-c;-mprocessor=32MZ2064DAR176;-fno-common;${INSTRUMENTED_TRACE_OPTIONS};${FUNCTION_LEVEL_PROFILING_OPTIONS};-DXPRJ_default=default;-mdfp=C:/Users/drewm/.mchp_packs/Microchip/PIC32MZ-DA_DFP/1.5.231;${CMSIS_PACK_INCLUDE}")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
function(compile_cpp_rule target)
    set(inputVar "${CC_PRE};-g;-mprocessor=32MZ2064DAR176;-frtti;-fexceptions;-fno-check-new;-fenforce-eh-specs;-fno-common;${INSTRUMENTED_TRACE_OPTIONS};${FUNCTION_LEVEL_PROFILING_OPTIONS};-DXPRJ_default=default;-mdfp=C:/Users/drewm/.mchp_packs/Microchip/PIC32MZ-DA_DFP/1.5.231;${CMSIS_PACK_INCLUDE}")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
function(link_rule target)
    set(inputVar "${MP_EXTRA_LD_PRE};-g;-mprocessor=32MZ2064DAR176;${INSTRUMENTED_TRACE_OPTIONS};${FUNCTION_LEVEL_PROFILING_OPTIONS};-DXPRJ_default=default;-Wl,--defsym=__MPLAB_BUILD=1,${MP_EXTRA_LD_POST},${MP_LINKER_FILE_OPTION},--no-code-in-dinit,,--no-dinit-in-serial-mem,,--memorysummary,memoryfile.xml;-mdfp=C:/Users/drewm/.mchp_packs/Microchip/PIC32MZ-DA_DFP/1.5.231")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_link_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
